// Tarefas de homologação por produto - serão preenchidas depois
// IMPORTANTE: Produtos que não aparecem aqui NÃO têm processo de homologação

// Função para dividir texto por vírgulas, respeitando parênteses
const splitByComma = (text) => {
  const parts = [];
  let current = '';
  let depth = 0;
  
  for (let i = 0; i < text.length; i++) {
    const char = text[i];
    
    if (char === '(') {
      depth++;
      current += char;
    } else if (char === ')') {
      depth--;
      current += char;
    } else if (char === ',' && depth === 0) {
      const trimmed = current.trim();
      if (trimmed) parts.push(trimmed);
      current = '';
    } else {
      current += char;
    }
  }
  
  const trimmed = current.trim();
  if (trimmed) parts.push(trimmed);
  
  return parts;
};

const parseTasksIntoSections = (tasks) => {
  const sections = [];
  let currentSection = null;

  tasks.forEach(task => {
    // Se a tarefa está em UPPERCASE completo ou começa com "ETAPA", "HOMOLOGAÇÃO" ou "SPRINT", é uma seção
    if (task === task.toUpperCase() || task.startsWith('ETAPA') || task.startsWith('HOMOLOGAÇÃO') || task.startsWith('SPRINT')) {
      if (currentSection) {
        sections.push(currentSection);
      }
      currentSection = { section: task, tasks: [] };
    } else if (currentSection) {
      // Divide a tarefa por vírgulas (respeitando parênteses)
      const subtasks = splitByComma(task);
      currentSection.tasks.push(...subtasks);
    }
  });

  if (currentSection) {
    sections.push(currentSection);
  }

  return sections;
};

// Mapa de produtos com suas tarefas de homologação
export const homologationTasksByProduct = {
  'e-Nota (Cloud)': parseTasksIntoSections([
    'CADASTROS',
    'Entidades',
    'Pessoas',
    'Usuários',
    'Auto de infração (Auto de infração e infrações)',
    'Base cadastral (Lista de serviços Lei 116/03, alíquota do Simples Nacional, taxas diversas, séries do RPS, unidades e contadores)',
    'Configurações (Gerais, pendências financeiras. créditos tributários, tomadores descontados, substitutos tributários, guias de pagamento, solicitações de acesso, liberação de RPS, carta de correção, saldos, mensagem ao prestador, integrações e gerenciador de certificado)',
    'Endereços (Bairros, condomínios, logradouros e loteamentos)',
    'Financeiros (Competências, convênios, indexadores, feriados e incentivos fiscais)',
    'Manutenção de incentivos fiscais',
    'Mensagens',
    'Relatórios personalizados',
    'Rotinas externas',
    'Scripts',
    'PROCESSOS',
    'Liberação',
    'Denúncia fiscal',
    'Prestadores',
    'Autorização para impressão de RPS',
    'Gerar competências',
    'Saldos (consultar saldos, lançar saldos. liberar saldos bloqueados, cancelar saldos e utilizar saldos por restituição)',
    'Créditos tributários (Liberar créditos, cancelar créditos, expirar créditos, gerar créditos, transferir créditos e gerar por script)',
    'Cancelar notas (Sem solicitação, com solicitação e estornar cancelamento)',
    'Substituir notas (Com solicitação e estornar substituição de nota fiscal)',
    'Manutenção de guias de pagamento (Vencimento das guias, cancelamentod as guias, integração das guias)',
    'Manutenções fiscais (Alteração de dedução fiscal e regime tributário, manutenção e remuneração de nota fiscal)',
    'Importação de arquivos (Optantes do simples nacional/SIMEI)',
    'Exportação de notas (Notas fiscais e TSE)',
    'Sincronizar cadastros',
    'Gerenciador de processos',
    'RELATÓRIOS',
    'Acessos (Acessos dos usuários, adesão ao sistema, denúncia fiscal e solicitação de acessos pendentes)',
    'Cadastrais (Bairros e usuários de prestadores)',
    'Créditos (Créditos tributários. extrato dos créditos tributários, créditos tributários por prestadores e créditos tributários por tomadores)',
    'Notas fiscais (Evolução das notas fiscais, maiores eminentes de notas fiscais, manutenções fiscais, notas fiscais, prestadores por notas, serviços prestados e substituições de notas fiscais)',
    'Pagamentos (Evolução da arrecadação, relação de pagamentos, e situação das guias de pagamentos)',
    'RPS (Autorização para impressão de RPS, RPS convertidos e não liberados e RPS convertidos fora do prazo)',
    'Serviços x CNAE',
    'Gerenciador de relatórios',
    'CONSULTAS',
    'Consulta geral',
    'Consultar notas',
    'Consultar lotes de RPS',
    'RPS convertidos fora do prazo',
    'Consultar créditos',
    'Consultar manutenção fiscal',
    'Consultar remunerações de nota fiscal',
    'Cobrança registrada',
    'Importação de nota nacional',
    'RESUMOS',
    'Estatísticos dos valores do ISS',
    'Notas emitidas',
    'GRÁFICOS',
    'Arrecadação por competência',
    'Notas fiscais por atividade',
    'Evolução das notas fiscais',
    'Notas fiscais emitidas por período',
    'Notas fiscais emitidas por prestador',
    'Notas fiscais emitidas por tomador',
    'ACESSOS',
    'Módulo contribuinte',
    'PRESTAÇÃO DE CONTAS',
    'Validar necessidade de campos relacionados às prestações de contas'
  ]),
  'Tributos (Cloud)': parseTasksIntoSections([
    'Módulo Imobiliário',
    'Validar Contribuintes',
    'Validar Econômico',
    'Validar Imóvel',
    'Créditos tributarios (Descrição, abreviatura, indexador, vincular com, transferência para dívida e receitas)',
    'Parcelas (Ano e crédito tributário)',
    'Moratórios (Tipo de lançamento, ano, crédito tributário e script)',
    'Compensatório (Tipo de lançamento, ano, crédito tributário e script)',
    'IPTU',
    'Tabelas de cálculo (Ano, descrição e origem dos campos)',
    'Cadastros gerais (Descrição, exibição, identificador, descrição da coluna e tipo)',
    'Planta de valores (Ano, nº do ato, distrito, bairro, logradouro, seção, face, inscrição imobiliária, indexador e valor do m²)',
    'Contribuintes (Dados pessoais e de endereço, documentos, campos adicionais e anexos)',
    'Construtoras (Descrição, número do CREA e data de registro)',
    'Imobiliárias (Nome e número do CRECI)',
    'Engenheiros/ Arquitetos (Nome, Nº dp CREA/ CAU e data de registro)',
    'Cartórios (Contribuinte e tipo)',
    'Agências (Número, dígito, nome, banco, CEP, município, logradouro, Nº, bairro)',
    'Bancos',
    'Indexadores (Descrição, sigla, tipo e movimentações)',
    'Limites de arrecadação (Topos de crédito, tipo de baixa, forma de pagamento, valor máximo de diferença, crédito)',
    'Convênios',
    'Documentos',
    'Imóveis',
    'Englobamento (Contribuinte, tipo de imóvel e filtros)',
    'Desmembramentos',
    'Remembramentos',
    'Geoprocessamento',
    'Obras',
    'Receita diversas (TIpo de serviço/crédito tributário, dados do serviço e lançamento)',
    'Requerimento/Manutenção de lançamento (Dados gerais, requerimento, receita de crédito e manutenção)',
    'Antecipação/Prorrogação de vencimentos (Definir filtros e prorrograr/antecipar vencimentos)',
    'Naturezas do texto jurídico (Descrição)',
    'Fontes de divulgação (Descrição e meio de comunicação)',
    'Atos',
    'Feriados (Descrição, abrangência, tipo e data)',
    'Unidades de medida (Símbolo, descrição singular, descrição plural, grandeza e gracionável?)',
    'Endereços (Faces, logradouros, condomínios, loteamentos, bairros, distritos, estados, municípios, seções e localidades)',
    'Benefícios fiscais (Descrição, tipo, ato/lei, validade e fundamentação legal)',
    'Motivos (Tipo, Lei/Ato e descrição)',
    'Materiais e serviços (Tipo, descrição, unidade de medida e tipo de cálculo)',
    'Guias (Tipo de lançamento, 2ª via?, crécdito tributário, convênio, data para pagamento, indexador, mostrar código de barras cobrar taxa de expediente?,)',
    'Transferência de imóveis (Informar dados, definir imóveis, configurar transferência e visualizar resumo)',
    'Não análisada',
    'Em análise',
    'Aguardando resposta',
    'Resposta recebida',
    'Deferida',
    'Indeferida',
    'Manutenção de pagamentos - pagamentos e saldos (Tipo de pagamento, tipo de inconsistência, nº do processo, observações, filtrar pagamento e gerar saldo)',
    'Cálculo (Ano e crédito tributário)',
    'Controle de saldo devedor',
    'Baixa automática/ estorno (Convênio, script, arquivo, baixa retroativa? data)',
    'Baixa manual/ estorno (Contribuinte, guia unificada, tipo de lançamento, exercício e Nº da parcela)',
    'Integração contábil (Validar integração no todo)',
    'Parcelamento de créditos (Dados gerais e filtros,  lançamentos a serem parcelados e confirmar parcelamento)',
    'Cancelamento/Reativação de documentos (Definir filtros e visualizar resultados)',
    'Encerramento',
    'Validar necessidade de campos relacionados às prestações de contas',
    'Módulo Dívida Ativa',
    'Parcelamento de créditos (Dados gerais, créditos tributários e taxas, parcelas)',
    'Documentos',
    'Agências (Número, dígito, nome, banco, CEP, município, logradouro, Nº, bairro)',
    'Bancos',
    'Indexadores (Descrição, sigla, tipo e movimentações)',
    'Limites de arrecadação (Topos de crédito, tipo de baixa, forma de pagamento, valor máximo de diferença, crédito)',
    'Convênios',
    'Receita diversas (TIpo de serviço/crédito tributário, dados do serviço e lançamento)',
    'Naturezas do texto jurídico (Descrição)',
    'Fontes de divulgação (Descrição e meio de comunicação)',
    'Atos',
    'Feriados (Descrição, abrangência, tipo e data)',
    'Unidades de medida (Símbolo, descrição singular, descrição plural, grandeza e gracionável?)',
    'Endereços (Faces, logradouros, condomínios, loteamentos, bairros, distritos, estados, municípios, seções e localidades)',
    'Motivos (Tipo, Lei/Ato e descrição)',
    'Benefícios fiscais (Descrição, tipo, Ato/Lei, validade e fundamentação legal)',
    'Materiais e serviços (Tipo, descrição, unidade de medida e tipo de cálculo)',
    'Guias (Tipo de lançamento, 2ª via?, crédito tributário, convênio, data para pagamento, indexador, mostrar código de barras?, cobrar taxa de expediente? e filtros)',
    'Livros de dívida ativa (Modelo e filtros)',
    'Termos de abertura/ encerramento do livro (Modelo e filtros)',
    'Baixa automática/ estorno - homologados e estornados (Convênio, script, arquivo baixa retroativa? e data)',
    'Baixa manual/ estorno (Contribuintes, guia unificada, tipo de lançamento, exercício e Nº da parcela)',
    'Integração contábil (Validar integração no todo)',
    'Inscrição em dívida (Débitos a serem inscritos e inscritos)',
    'Estorno de inscrição (Abertos e estornados)',
    'Parcelamento de créditos - Quitados e cancelados (Dados gerais e filtros,  lançamentos a serem parcelados e confirmar parcelamento)',
    'Anistias (Tipo, data, número do processo, fórmula, motivo, observações e filtros)',
    'Cancelamentos (Tipo, data, número do processo, fórmula, motivo, observações e filtros)',
    'Prescrições (Tipo, data, número do processo, fórmula, motivo, observações e filtros)',
    'Remissões (Tipo, data, número do processo, fórmula, motivo, observações e filtros)',
    'Suspensões (Tipo, data, número do processo, fórmula, motivo, observações e filtros)',
    'Prestações diversas (Tipo, data, número do processo, fórmula, motivo, observações e filtros)',
    'Transferência de dívida (Validar dívidas transferidas e processo de transferência)',
    'Cancelamento/ reativação de documentos  (Status, natureza, Nº do documento, modelo e contribuintes)',
    'Encerramento',
    'Validar necessidade de campos relacionados às prestações de contas',
    'Módulo Mobiliário',
    'TABELAS',
    'BASE CADASTRAL',
    'PESSOAS',
    'LANÇAMENTOS',
    'DOCUMENTOS',
    'FINANCEIRO',
    'Bancos',
    'TAXAS',
    'EMPRESAS',
    'CADASTROS AUXILIARES',
    'EMISSÃO',
    'CONSULTAS',
    'MOVIMENTAÇÃO FINANCEIRA',
    'MANUTENÇÕES',
    'ENCERRAMENTO MENSAL',
    'PRESTAÇÃO DE CONTAS'
  ]),
  'Procuradoria (Cloud)': parseTasksIntoSections([
    'AGENDA',
    'Validar funcionabilidade da agenda',
    'PESSOAS',
    'Contribuintes (Dados pessoais, dados de endereço, documentos e anexos)',
    'Referentes (Tipo, código, contribuinte, logradouro, número, bairro, município, corresponsável, proprietários, quadra, lote, inscrição imobiliária e complemento)',
    'Cartórios (Nome e tipo)',
    'Advogados e procuradores (Tipo, nome, inscrição na OAB, seccional OAB, complemento OAB e usuário)',
    'FINANCEIRO',
    'Agências (Número, dígito, nome, banco, CEP, município, logradouro, Nº, bairro)',
    'Bancos',
    'Convênios (Descrição, número, banco, agência, fórmula, modelo de carne, conta bancária. créditos tributarios, pode utilizar em parcelamentos? usa validade para número de baixa?, validade do número de baixa. homologar baixa e mensagens)',
    'Créditos tributários',
    'CADASTROS AUXILIARES',
    'Endereços (Faces, logradouros, condomínios, loteamentos, bairros, distritos, estados, municípios, seções e localidades)',
    'Áreas e assuntos (Código e descrição)',
    'Locais de tramitação (Tribunal)',
    'Grupos de trabalho (Descrição do grupo, data de ativação, áreas e pessoas que fazem parte do grupo)',
    'Classes (Código e descrição)',
    'Motivos (Descrição e tipo)',
    'CONTROLE DE DOCUMENTOS',
    'Cancelamento/ Reativação de documentos (Validar documentos ativos e cancelados)',
    'Modelos de petições intermediárias (Validar petições)',
    'Documentos emitidos (Certidão de dívida ativa, petição inicial e petição intermediária)',
    'DÍVIDAS',
    'Dívidas ativas (Sem certidão, com certidão, com petição,  protestada, protestada com petição, executada, executada e protestada)',
    'Processos  (execuções fiscais. quitadas/canceladas, parceladas/ suspensas e suspensas com dívidas em aberto)',
    'GERENCIADOR DE PROTESTOS',
    'Protestos (protestos, quitadas/ canceladas, parceladas/ suspensas)',
    'Validar necessidade de campos relacionados às prestações de contas',
    'EMISSÃO',
    'CONSULTAS',
    'MOVIMENTAÇÃO FINANCEIRA',
    'MANUTENÇÕES',
    'ENCERRAMENTO MENSAL',
    'PRESTAÇÃO DE CONTAS'
  ]),
  'Livro Eletrônico': parseTasksIntoSections([
    'CADASTROS',
    'Entidade',
    'Configurações (Gerais, fórmulas, autos de infrações, notas avulsas, certidão negativa, solicitações de acesso, configurações auxiliares e integrações)',
    'Pessoa',
    'Contribuintes',
    'Contadores',
    'Gráficas',
    'Financeiros (Competências, convênios, indexadores, feriados e incentivos fiscais)',
    'Base cadastral (Lista de serviços da lei 116/03, alíquotas do simples nacional, faixas do IRRF, plano de contas, despesas, materiais, taxas diversas, motivos da alteração de alíquota, entidades especiais, intes de ISS fixo e séries)',
    'Auto de infração (Infrações e autos de infrações)',
    'Endereços (Bairros, condemínios, logradouros e loteamentos)',
    'Fiscalizações por período',
    'PROCESSOS',
    'Liberação de acesso',
    'AIDF (Liberação de AIDF e Validação de recibos de AIDF)',
    'Contador (Desvínculo de contador e transferência de contador)',
    'Notas Avulsas',
    'Guias Tributos Cloud',
    'Saldos (Consultar saldos, lançar saldos, liberar saldos bloqueados, bloquear saldos liberados, cancelar saldos e utilizar saldos por restituição)',
    'Encerramento de declarações',
    'Reabertura das declarações (Serviços e despesas)',
    'Análise das declarações  (Gerenciados de pendências e cruzamento de documentos)',
    'Alteração cadastral',
    'Sincronizar dados',
    'Gerenciador de processos',
    'RELATÓRIOS',
    'Movimentação cadastral (Contribuintes e plano de contas)',
    'Movimentação fiscal',
    'Análise dos documentos',
    'Análise dos documentos importados',
    'Serviços prestados não declarados pelo tomador',
    'Serviços prestados por município',
    'Serviços tomados não declarados pelo prestador',
    'Serviços tomados por município',
    'Situação dos contribuintes',
    'Encerramento simples nacional',
    'Taxas diversas',
    'Cruzamento entre declarações dos serviços e dos valores recebidos em cartão',
    'Movimentação financeira (Arrecadações de ISS, lançamentos de ISS, arrecadações e lançamentos de ISS, maiores prestadores, maiores tomadores, maiores atividades, situação das guias de pagamento, guias registradas e maiores contribuintes por condições em cartão)',
    'Contador (Certidão de desvínculo de contador, comprovante de transferência de contador, contribuintes por contador e transferências de contador)',
    'Conferência do livro do ISS',
    'Recibo de ISS retido/por substituição',
    'Recibos de declarações',
    'Fiscalização por período',
    'AIDF (Documentos fiscais liberados e não declarados, documentos fiscais não autorizados e relatório de AIDF)',
    'Gerenciador de relatórios',
    'CONSULTAS',
    'Cobrança registrada',
    'ACESSO',
    'Módulo contribuinte',
    'PRESTAÇÃO DE CONTAS',
    'Validar necessidade de campos relacionados às prestações de contas',
    'EMISSÃO',
    'CONSULTAS',
    'MOVIMENTAÇÃO FINANCEIRA',
    'MANUTENÇÕES',
    'ENCERRAMENTO MENSAL',
    'PRESTAÇÃO DE CONTAS'
  ]),
  'Protocolo (Cloud)': parseTasksIntoSections([
    'PESSOAS',
    'Nome',
    'CPF/CNPJ',
    'Nome Social',
    'Endereços',
    'Telefone',
    'E-mail',
    'Filiações',
    'Estado Civil',
    'Sexo',
    'Data de nascimento',
    'Data de óbito',
    'ORGANOGRAMAS',
    'Configuração de organograma',
    'Usuários/Responsáveis do organograma',
    'ENDEREÇOS',
    'Países',
    'Estados',
    'Municipios',
    'Bairros',
    'Tipo de logradouro',
    'Logradouros',
    'Condominio',
    'CEP do logradouro',
    'Bairro do logradouro',
    'GESTÃO DE PROCESSOS',
    'Processo',
    'Confirmações',
    'Andamentos',
    'Transferências',
    'Estorno de processos',
    'Localização do processo (processo-organograma-usuario)',
    'Processo-Volume',
    'Movimentações',
    'Classificação',
    'Arquivamentos',
    'Processo Organograma',
    'Partes interessadas do processo',
    'Geolocalização',
    'Juntamentos de processos',
    'Guias de pagamento',
    'Parecer',
    'Deferidos',
    'Indeferido',
    'Confirmado',
    'Anulado',
    'Conhecimento',
    'Parcial',
    'Outros',
    'ASSUNTOS',
    'Validar informações adicionais',
    'Configurações do Assunto',
    'Documentos do assunto',
    'Guias de pagamento',
    'Taxas do assunto',
    'EMISSÃO',
    'CONSULTAS',
    'MOVIMENTAÇÃO FINANCEIRA',
    'MANUTENÇÕES',
    'ENCERRAMENTO MENSAL',
    'PRESTAÇÃO DE CONTAS'
  ]),
  'Portal Gestor (Cloud)': parseTasksIntoSections([
    'CONTÁBIL',
    'Configurações gerais',
    'Cargas',
    'Índices',
    'ARRECADAÇÃO',
    'Configurações gerais',
    'Cargas',
    'Índices',
    'Configurações gerais',
    'Cargas',
    'Índices',
    'PESSOAL',
    'Configurações gerais',
    'Cargas',
    'Índices',
    'SAÚDE',
    'Configurações gerais',
    'Cargas',
    'Índices',
    'EDUCAÇÃO',
    'Configurações gerais',
    'Cargas',
    'Índices',
    'CONTRATOS',
    'Configurações gerais',
    'Cargas',
    'Índices',
    'Processo-Volume',
    'Movimentações',
    'Classificação',
    'Arquivamentos',
    'Processo Organograma',
    'Partes interessadas do processo',
    'Geolocalização',
    'Juntamentos de processos',
    'Guias de pagamento',
    'Deferidos',
    'Indeferido',
    'Confirmado',
    'Anulado',
    'Conhecimento',
    'Parcial',
    'Outros',
    'Validar informações adicionais',
    'Configurações do Assunto',
    'Documentos do assunto',
    'Guias de pagamento',
    'Taxas do assunto',
    'EMISSÃO',
    'CONSULTAS',
    'MOVIMENTAÇÃO FINANCEIRA',
    'MANUTENÇÕES',
    'ENCERRAMENTO MENSAL',
    'PRESTAÇÃO DE CONTAS'
  ]),
  'Contábil (Cloud)': parseTasksIntoSections([
    'PARÂMETROS GERAIS',
    'Parâmetros (Efetivar retenção, Ordem de baixa)',
    'Portal da transparência fly (Informações Gerais, Envio de Relatórios)',
    'Portal da transparência cloud (Informações Gerais, Envio de Relatórios)',
    'EFD-Reinf (É ente federativo responsável?, Entidade beneficiente/isenta de contribuições sociais, Responsável pelas informações EFD-Reinf, Chave de Acesso, Script)',
    'ESCRITURAÇÃO',
    'Plano de contas (Configuração, Máscara,Tipo,Vigência,Descrição,Função)',
    'Eventos contábeis (Número, Vigência, Título, Documento, Abrangência,Aplicabilidade,Condição,Histórico,Histórico de Estorno)',
    'Regras de documentos (Descrição, Status, Documento)',
    'Contas Correntes (Descrição, Lote, Vigência, Condição, Componentes)',
    'Componentes (Descrição, Configuração, Fonte de Dados, Campo, Filtro, Documentos)',
    'Equivalências (Conta Contábil, Classificação)',
    'Itens de equivalência (Descrição, Documento, Campo, Item)',
    'Processos (Configuração, Descrição, Tipo, Script)',
    'FUNCIONAL PROGRAMÁTICA',
    'Programas (Programa, Público-Alvo, Objetivos do Programa)',
    'Configuração de Funcionais (Configuração, Número, Descrição)',
    'Ações (Ação, Tipo, Descrição, Finalidade)',
    'PESSOAS',
    'Assinantes (Nome, CPF, Função, Complemento)',
    'Credores (Informações Gerais, Campos Adicionais)',
    'Ordenadores de Despesa (Informações Gerais, Campos Adicionais)',
    'Responsáveis (Informações Gerais, Campos Adicionais)',
    'ASSINATURAS',
    'Assinaturas (Data inicial, data final, grupo, organograma, assinantes e campos adicionais)',
    'ATOS',
    'Tipos de Atos (Informações Gerais, Campos Adicionais)',
    'Atos (Número, Tipo, Natureza do texto jurídico, Data de criação, Data a vigorar, Data da revogação, Data da sanção, Data de publicação, Número do diário oficial, Fontes de divulgação e Ementa)',
    'Naturezas de Texto Jurídico (Informações Gerais, Campos Adicionais)',
    'Fontes de divulgação (Nome e meio de comunicação)',
    'ESTRUTURA ORGANIZACIONAL',
    'Organogramas (Configuração, Número, Descrição, Tipo de Administração, Campos Adicionais)',
    'Entidade (Informações Gerais, Campos Adicionais)',
    'NATUREZAS',
    'Receitas (Configuração, Informações Gerais, Campos Adicionais)',
    'Despesas (Configuração, Informações Gerais, Campos Adicionais)',
    'CONTROLE',
    'Localizadores (Descrição)',
    'Recursos (Configuração, Informações Gerais, Campos Adicionais)',
    'Retenções (Informações Gerais, Campos Adicionais)',
    'Receitas Extraorçamentárias (Informações Gerais, Campos Adicionais)',
    'Comprovantes (Informações Gerais, Campos Adicionais)',
    'Diárias (Informações Gerais, Campos Adicionais)',
    'BANCÁRIOS',
    'Agências bancárias (Informações Gerais, Campos Adicionais)',
    'Contas bancárias (Informações Gerais, Campos Adicionais)',
    'CADASTROS AUXILIARES',
    'Adicionando projeção atuarial previdenciária (Informações Gerais, Campos Adicionais)',
    'Adicionando projeção atuarial plano financeiro (Informações Gerais, Campos Adicionais)',
    'Unidades de medida (Informações Gerais, Campos Adicionais)',
    'Origens de alterações de despesas (Informações Gerais, Campos Adicionais)',
    'Tipos de comprovante (Informações Gerais, Campos Adicionais)',
    'Deduções das receitas (Informações Gerais, Campos Adicionais)',
    'Endereços (Logradouros, Condomínios, Loteamentos, Bairros, Distritos, Estados, Municípios)',
    'Tipos de Dívida (Informações Gerais, Campos Adicionais)',
    'Tipos de Precatórios (Informações Gerais, Campos Adicionais)',
    'Tipos de Responsáveis (Informações Gerais, Campos Adicionais)',
    'Tipos de Administração (Informações Gerais, Campos Adicionais)',
    'Tipos de alteração de receita (Informações Gerais, Campos Adicionais)',
    'Transações financeiras (Informações Gerais, Campos Adicionais)',
    'Tipos de bloqueios (Informações Gerais, Campos Adicionais)',
    'Tipos de aplicação (Informações Gerais, Campos Adicionais)',
    'Despesas não previstas na LOA (Informações Gerais, Campos Adicionais)',
    'Receitas não previstas na LOA (Informações Gerais, Campos Adicionais)',
    'Desmembramento de receitas (Informações Gerais, Campos Adicionais)',
    'Saldos iniciais extraorçamentários (Informações Gerais, Campos Adicionais)',
    'RECEITA',
    'Arrecadações (Informações Gerais, Campos Adicionais)',
    'Arrecadações Extras Orçamentárias (Informações Gerais, Campos Adicionais)',
    'Lançamentos de receita (Data, Receita, Valor, Descrição)',
    'Devoluções de receita (Número, Data, Dedução, Valor, Credor, Conta Bancária Credor, Finalidade, Receita, Valor, Data de vencimento, Baixa)',
    'Alteração orçamentária da receita (Informações Gerais, Campos Adicionais)',
    'CONTROLE',
    'Prestação de contas - Adiantamentos e diárias',
    'Dívidas (Informações Gerais, Campos Adicionais)',
    'Contratos de Rateio (Informações Gerais, Campos Adicionais)',
    'Prestação de contas de consórcio (Número, Consórcio, Contrato, Recurso, Função, Subfunção, Natureza da despesa)',
    'INTERAÇÕES',
    'Gerenciador de integrações',
    'DESPESA',
    'Empenhos (Informações Gerais, Campos Adicionais)',
    'Liquidações (Informações Gerais, Campos Adicionais)',
    'Pagamentos (Informações Gerais, Campos Adicionais)',
    'Despesa Extra (Informações Gerais, Campos Adicionais)',
    'Alterações orçamentárias da despesa (Informações Gerais, Campos Adicionais)',
    'Bloqueios/Desbloqueios da despesa (Informações Gerais, Campos Adicionais)',
    'PROGRAMAÇÃO FINANCEIRA',
    'Programação financeira da receita',
    'Programação financeira da despesa',
    'PERÍODO FINANCEIRO',
    'Período financeiro (Abertura, Encerramento, Configuração)',
    'ESCRITURANDO',
    'Escriturações de documentos (Informações Gerais, Campos Adicionais)',
    'Balancete dinâmico',
    'Períodos da escrituração (Abertura, Encerramento, Configuração)',
    'PRESTAÇÃO DE CONTAS',
    'Validar necessidade de campos relacionados às prestações de contas'
  ]),
  'Planejamento (Cloud)': parseTasksIntoSections([
    'PLANEJAMENTO',
    'PPA (Composição da receita e despesa, Composição da receita, Composição da despesa)',
    'LDO (Composição da receita e despesa, Composição da receita, Composição da despesa e Nível da natureza da despesa)',
    'LOA (Composição da receita, Nível da natureza da despesa, Gerar número reduzido para "receitas e despesas")',
    'ESCRITURAÇÃO',
    'FUNCIONAL PROGRAMÁTICA',
    'FUNCIONAL PROGRAMÁTICA',
    'PPA (Receitas, Despesas, Programas, Ações, Organogramas e Recursos)',
    'LDO (Receitas, despesas, programas, ações, organogramas, recursos, transferências financeiras, cernários macroeconômicos e limites)',
    'LOA (Receitas, despesas, programas, ações, organogramas, recursos, transferências financeiras e limites)',
    'Função (número e descrição)',
    'Subfunções (número e descrição)',
    'PPA (Receitas, Despesas, Programas, Ações, Organogramas e Recursos)',
    'LDO (Receitas, despesas, programas, ações, organogramas, recursos, transferências financeiras, cernários macroeconômicos e limites)',
    'LOA (Receitas, despesas, programas, ações, organogramas, recursos, transferências financeiras e limites)',
    'Atuários (Nome, CPF/CNPJ, Registro do IBA, Endereços e Campos Adicionais)',
    'PESSOAS',
    'Assinantes (Nome, CPF, Função e Complemento)',
    'Responsáveis (Nome, CPF, Descrição do cargo, Tipo, Endereço, Telefone, E-mails, Registro, RG, Anexos e Campos adicionais)',
    'ASSINATURAS',
    'Assinaturas (Data inicial, Data final, Grupo, Organograma(s) e Assinantes)',
    'Grupo de configuração de assinaturas (Descrição)',
    'INDICADORES',
    'Indicadores (Descrição e campos adicionais)',
    'Indicadores de programas (Programa, indicador, unidade de medida, índice de referência, data de apuração, fonte, observações, índices esperados e campos adicionais)',
    'ESTRUTURA ORGANIZACIONAL',
    'Organogramas (Número, descrição e tipo de administração)',
    'Entidades (Dados cadastrais da entidade)',
    'BASE ESTRATÉGICA',
    'Equipes de planejamento (Descrição, ato de nomeação, período e atribuições)',
    'Audiências (Tema, ato, data e hora, primeira convocação, situação, equipe de planejamento, endereços beneficiados, tipo de audiência, endereço da audiência, assunto e campos adicionais)',
    'Orientações estratégicas (Denominação, Equipe de planejamento, Data, Situação, Orientação e Justificativa)',
    'Sugestões (Origem, Tipo, Data, Categoria, Endereço beneficiado, Assunto, Sugestão apresentada), avaliar as sugestões em avaliação, viabilidade e concluidas.',
    'Macro-objetivos (Denominação e Descrição)',
    'Objetivos estratégicos (Objetivo, Macro objetivos e Definição do objetivo)',
    'CADASTROS AUXILIARES',
    'ATOS',
    'ATOS',
    'Tipos de atos (Descrição e Classificação)',
    'Atos (Número, Tipo, Natureza do texto jurídico, Data de criação, Data a vigorar, Data da revogação, Data da sanção, Data de publicação, Número do diário oficial, Fontes de divulgação e Ementa)',
    'Natureza de texto jurídico (Descrição e campos adicionais)',
    'Fontes de divulgação (Nome e meio de comunicação)',
    'PPA (Receitas, Despesas, Programas, Ações, Organogramas e Recursos)',
    'LDO (Receitas, despesas, programas, ações, organogramas, recursos, transferências financeiras, cernários macroeconômicos e limites)',
    'LOA (Receitas, despesas, programas, ações, organogramas, recursos, transferências financeiras e limites)',
    'Recursos (Número, Tipo, Descrição, Marcadores e Campos adicionais)',
    'NATUREZAS',
    'Receita (Número, tipo, descrição, marcadores e campos adicionais)',
    'Despesa (Número, tipo, descrição, marcadores e campos adicionais)',
    'CADASTROS AUXILIARES',
    'Unidades de medida (Abreviatura e descrição)',
    'Origens de alterações de despesa (Descrição e enquadramento legal)',
    'Deduções da receita (Descrição e tipo)',
    'Endereços (Informações cadastrais de Logradouros, Condomínios, Bairros, Distritos, Estados e Municípios)',
    'Tipos de compensações (Descrição)',
    'Tipos de renúncias físicas (Descrição)',
    'Tipos de administração (Descrição, natureza jurídica, tipo de administração e poder)',
    'Tipos de alteração de receita (Descrição e tipo)',
    'Tipos de resultados nominais (Descrição)',
    'Tipos de riscos fiscais (Descrição e classificação na LRF)',
    'Tipos de responsáveis (Descrição)',
    'Despesas não previstas na LOA',
    'Marcadores (Descrição e lote)',
    'Em elaboração (Número, data, crédito, despesa, tipo de crédito, finalidade, anexos e campos adicionais)',
    'Anulada (Número, data, crédito, despesa, tipo de crédito, finalidade, anexos e campos adicionais)',
    'Sancionada (Número, data, crédito, despesa, tipo de crédito, finalidade, anexos e campos adicionais)',
    'Em tramitação de alteração orçamentaria (Número, data, crédito, despesa, tipo de crédito, finalidade, anexos e campos adicionais)',
    'Enviada p/ alteração orçamentária (Número, data, crédito, despesa, tipo de crédito, finalidade, anexos e campos adicionais)',
    'Limites das despesas da LOA (Número, valor, itens e motivo)',
    'PPA',
    'Receitas (Natureza da receita, entidade, meta financeira quadrienal, meta financeira anual, deduções, marcadores e campos adicionais)',
    'Despesas (Entidade, organograma, programa, ação, função, subfunção, meta financeira quadrienal, meta financeira anual, metas físicas, marcadores e campos adicionais)',
    'Execução das metas físicas',
    'Avaliação do PPA (Exercício, equipe de planejamento, avaliação da gestão do plano e campos adicionais)',
    'LDO',
    'Receitas (Natureza da receita, entidade, meta financeira, deduções, marcadores e campos adicionais)',
    'Despesas (Entidade, organograma, programa, ação, função, subfunção, meta financeira, metas físicas, marcadores e campos adicionais)',
    'Expansão de despesas (Despesa, descrição, atos, valor, projeção 2030, projeção 2031)',
    'Projeções atuariais previdenciárias (Atuário. registro do IBA, data base de cálculo e saldo financeiro em 2025)',
    'Projeções atuariais plano financeiro (Atuário. registro do IBA, data base de cálculo e saldo financeiro em 2025)',
    'Resultados nominais (Tipo resultado, exercícioatual, anos anteriores e próximos anos)',
    'Riscos Fiscais (Tipo, entidade, organograma, detalhamento, providência, exercício atual, próximos anos)',
    'Renúncias físicas (Receita, tipo, localizador, ato regulamentar,  descrição, exercício atual, próximos anos)',
    'Metas fiscais da receita',
    'Metas fiscais da despesa',
    'Transferências financeiras (Entidade, organograma (origem). Destino, entidade, organograma, recurso, finalidade e valor (destino).',
    'LOA',
    'Receitas (Natureza da receita, entidade,  organograma, meta financeira, especificação, recursos, deduções, marcadores e campos adicionais)',
    'Despesas (Entidade, organograma, programa, ação, função, subfunção, meta financeira, metas físicas e campos adicionais)',
    'Transferências financeiras (Entidade, organograma (origem). Destino, entidade, organograma, recurso, finalidade e valor (destino).',
    'Alterações orçamentárias da receita (Tipo de alteração, finalidade, receita, impacto da alteração e valor)',
    'Alterações orçamentárias da despesa',
    'Créditos em elaboração (Crédito, despesa, tipo de crédito, finalidade e campos adicionais)',
    'Propostas (Crédito, despesa, tipo de crédito, finalidade e campos adicionais)',
    'No legislativo (Crédito, despesa, tipo de crédito, finalidade e campos adicionais)',
    'Sancionada (Crédito, despesa, tipo de crédito, finalidade e campos adicionais)',
    'Solicitações de despesas',
    'Limites na LOA',
    'Manutenção',
    'Programação financeira da receita',
    'Programação financeira da despesa',
    'PROCESSOS',
    'Cópia de PPA',
    'Relatório da cópia de PPA',
    'Cópia do LDO',
    'Relatório da cópia de LDO',
    'PRESTAÇÃO DE CONTAS',
    'PRESTAÇÃO DE CONTAS'
  ]),
  'Tesouraria (Cloud)': parseTasksIntoSections([
    'PARÂMETROS GERAIS',
    'Parâmetros (Reconhecer documento, controlar movimentação diária)',
    'Movimentos (Data, observação e campos adicionais)',
    'Remessas bancárias (Descrição, script, banco e campos adicionais)',
    'Critérios de conciliação (Descrição)',
    'Portal da transparência fly (Chave de aceesso, e-mail de retorno, exercício do primeiro envio, data e hora do último envio, script)',
    'IMPLANTAÇÃO',
    'Parâmetros da implantação (Data da implantação)',
    'Saldo inicial em dinheiro (Data, valor, finalidade e recursos)',
    'BANCÁRIOS',
    'Agências (Banco, nome da agência, número, dígito, CEP, logradouro, número, bairro, município e campos adicionais)',
    'Contas (Banco, marcadores, anexos e campos adicionais)',
    'Cheques (Conta bancária, número inicial, número final, quantidade, observação e campos adicionais)',
    'CONTROLE',
    'Recursos (Número, tipo, descrição, recurso de superávit financeiro, marcadores e campos adicionais)',
    'Retenções (Descrição, tipo, credores, naturezas da despesa e campos adicionais)',
    'Receitas extraorçamentárias (Descrição, tipo, recursos e campos adicionais)',
    'PESSOAS',
    'Assinantes (Nome, CPF, função e complemento)',
    'Credores (Nome, CPF/CNPJ, data de inclusão, dados pessoais, documentos, contas bancárias. EFD-REINF)',
    'Responsáveis (Nome, CPF, descrição do cargo, tipo, dados pessoaism anexos e campos adicionais)',
    'ESTRUTURA ORGANIZACIONAL',
    'Organogramas (Número, Descrição, Tipo de Administração e Campos Adicionais)',
    'Entidade (Informações Gerais e Campos Adicionais)',
    'ASSINATURAS',
    'Assinaturas (Data inicial, data final, grupo, organograma, assinantes e campos adicionais)',
    'Grupo de configuração de assinaturas (Descrição)',
    'CADASTROS AUXILIARES',
    'Deduções da receita (Descrição, tipo e campos adicionais)',
    'Tipos de movimentos (Descrição, tipo e campos adicionais)',
    'Tipos de aplicação (Descrição e campos adicionais)',
    'Tipos de documentos (Descrição e campos adicionais)',
    'Tipos de administração (Descrição, natureza jurídica, tipo de administração, poder e campos adicionais)',
    'Tipos de responsáveis (Descrição e campos adicionais)',
    'Transações financeiras (Descrição, tipo e campos adicionais)',
    'Endereços (Informações cadastrais de Logradouros, Condomínios, Bairros, Distritos, Estados e Municípios)',
    'PROCESSOS',
    'Arrecadações (Data, transação, número do documento, valor, conta bancária, tipo de conta, especificação, campos adicionais e pendências)',
    'Pagamentos',
    'A pagar (Empenho, subempenho, despesa extra e devolução receita)',
    'Pago (Empenho, subempenho, despesa extra e devolução receita)',
    'Devoluções da receita (Número, data, dedução, valor, credor, conta bancária credor, finalidade, receita, valor, data de vencimento)',
    'Ajustes de recursos (Data, categoria, valor, recurso de origem, recurso de destino e finalidade)',
    'BANCÁRIOS',
    'Gestão (Aplicação e Configuração de emissão)',
    'Conciliações (Conta bancária, tipo de conta, período, saldo financeiro, saldo do extrado, saldo a conciliar, data conclusão, pendência, anexos e campos adicionais)',
    'Transferências (Número, data, conta bancária origem, tipo conta origem, recurso, valor, conta bancária destino, tipo conta destino, finalidde, data de vencimento, baixa e campos adicionais)',
    'PRESTAÇÃO DE CONTAS',
    'Validar necessidade de campos relacionados às prestações de contas'
  ]),
  'Convênios (Cloud)': parseTasksIntoSections([
    'ATOS',
    'Tipos de Atos (Descrição, classificação e campos adicionais)',
    'Atos (Número, Tipo, Natureza do texto jurídico, Data de criação, Data a vigorar, Data da revogação, Data da sanção, Data de publicação, Número do diário oficial, Fontes de divulgação e Ementa)',
    'Naturezas de Texto Jurídico (Descrição e campos Adicionais)',
    'Fontes de divulgação (Nome e meio de comunicação)',
    'PARTICIPANTES',
    'Concedentes (Nome, CPF/CNPJ e esfera administrativa)',
    'Convenentes (Nome e CPF/CNPJ)',
    'Certidões de convenentes (Convenente, número, tipo, data de emissão e data de validade)',
    'Certidões da entidade (Número, tipo, data de emissão, data de validade e campos adicionais)',
    'CONTROLE',
    'Comprovantes (Tipo do comprovante, Nº do comprovante, Data de emissão, série do comprovante, código de validação do comprovante, convenente, valor brut, valor do desconto, valor líquido e finalidade)',
    'ESTRUTURA ORGANIZACIONAL',
    'Entidades (Informações gerais e campos adicionais)',
    'CADASTROS AUXILIARES',
    'Modalidades (Descrição)',
    'Responsáveis (Nome, CPF, tipo e campos adicionais)',
    'Tipos de certidões (Descrição)',
    'Tipos de comprovantes (Descrição e tipo)',
    'Tipos de aditivos (Descrição, classificação e tipo)',
    'Tipos de situação (Descrição)',
    'Tipos de repasses (Descrição e classificação)',
    'Tipos de responsáveis (Descrição)',
    'CONVÊNIOS',
    'Recebidos (Número, valor do repasse, valor de contrapartida, valor global, objeto, período, data da assinatura, conta bancária, modalidade, concedente, ato autorizativo, certidões, responsáveis, anexos e campos adicionais). Validar os em prestação e os concluidos.',
    'Repassados',
    'Convênio (Número, Valor repassado, valor de contrapartida, valor global, objeto, período, data da assinatura, tipo, modalidade, conta bancária, convenente, ato autorizativo, certidões, responsáveis, anexos e campos adicionais)',
    'Formalização e execução (Convênios e aditivos)',
    'Prestação de contas (A comprovar, em comprovação e comprovado)',
    'Concluído (Convenios e aditivos)',
    'PRESTAÇÃO DE CONTAS',
    'Validar necessidade de campos relacionados às prestações de contas'
  ])
};

// Normaliza o nome do produto removendo "(Cloud)" e caracteres especiais
const normalizeProductName = (name) => {
  if (!name) return '';
  
  let normalized = name
    .toLowerCase()
    .replace(/\(cloud\)/gi, '')
    .replace(/[()]/g, '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '') // Remove acentos
    .trim()
    .replace(/\s+/g, ' ');
  
  // Mapeamento de sinônimos
  const synonyms = {
    'contabilidade': 'contabil',
    'tesouraria': 'tesouraria'
  };
  
  for (const [key, value] of Object.entries(synonyms)) {
    if (normalized === key) {
      normalized = value;
      break;
    }
  }
  
  return normalized;
};

// Função para buscar tarefas por nome de produto
// Retorna null se o produto não tiver processo de homologação
export const getDefaultTasksForProduct = (productName) => {
  if (!productName) return null;
  
  const normalizedInput = normalizeProductName(productName);
  
  // Busca APENAS match exato (considerando com e sem Cloud)
  for (const [key, tasks] of Object.entries(homologationTasksByProduct)) {
    const normalizedKey = normalizeProductName(key);
    if (normalizedKey === normalizedInput) {
      return tasks;
    }
  }
  
  // Se não encontrou match exato, retorna null (produto sem homologação)
  return null;
};

// Verifica se um produto tem processo de homologação
export const productHasHomologation = (productName) => {
  return getDefaultTasksForProduct(productName) !== null;
};