// Tarefas de homologação por produto - serão preenchidas depois
// IMPORTANTE: Produtos que não aparecem aqui NÃO têm processo de homologação

// Função para dividir texto por vírgulas, respeitando parênteses
const splitByComma = (text) => {
  const parts = [];
  let current = '';
  let depth = 0;
  
  for (let i = 0; i < text.length; i++) {
    const char = text[i];
    
    if (char === '(') {
      depth++;
      current += char;
    } else if (char === ')') {
      depth--;
      current += char;
    } else if (char === ',' && depth === 0) {
      const trimmed = current.trim();
      if (trimmed) parts.push(trimmed);
      current = '';
    } else {
      current += char;
    }
  }
  
  const trimmed = current.trim();
  if (trimmed) parts.push(trimmed);
  
  return parts;
};

const parseTasksIntoSections = (tasks) => {
  const sections = [];
  let currentSection = null;

  tasks.forEach(task => {
    // Se a tarefa está em UPPERCASE completo ou começa com "ETAPA", "HOMOLOGAÇÃO" ou "SPRINT", é uma seção
    if (task === task.toUpperCase() || task.startsWith('ETAPA') || task.startsWith('HOMOLOGAÇÃO') || task.startsWith('SPRINT')) {
      if (currentSection) {
        sections.push(currentSection);
      }
      currentSection = { section: task, tasks: [] };
    } else if (currentSection) {
      // Divide a tarefa por vírgulas (respeitando parênteses)
      const subtasks = splitByComma(task);
      currentSection.tasks.push(...subtasks);
    }
  });

  if (currentSection) {
    sections.push(currentSection);
  }

  return sections;
};

// Mapa de produtos com suas tarefas de homologação
export const homologationTasksByProduct = {
  'e-Nota (Cloud)': parseTasksIntoSections([
    'CADASTROS',
    'Entidades',
    'Pessoas',
    'Usuários',
    'Auto de infração (Auto de infração e infrações)',
    'Base cadastral (Lista de serviços Lei 116/03, alíquota do Simples Nacional, taxas diversas, séries do RPS, unidades e contadores)',
    'Configurações (Gerais, pendências financeiras. créditos tributários, tomadores descontados, substitutos tributários, guias de pagamento, solicitações de acesso, liberação de RPS, carta de correção, saldos, mensagem ao prestador, integrações e gerenciador de certificado)',
    'Endereços (Bairros, condomínios, logradouros e loteamentos)',
    'Financeiros (Competências, convênios, indexadores, feriados e incentivos fiscais)',
    'Manutenção de incentivos fiscais',
    'Mensagens',
    'Relatórios personalizados',
    'Rotinas externas',
    'Scripts',
    'PROCESSOS',
    'Liberação',
    'Denúncia fiscal',
    'Prestadores',
    'Autorização para impressão de RPS',
    'Gerar competências',
    'Saldos (consultar saldos, lançar saldos. liberar saldos bloqueados, cancelar saldos e utilizar saldos por restituição)',
    'Créditos tributários (Liberar créditos, cancelar créditos, expirar créditos, gerar créditos, transferir créditos e gerar por script)',
    'Cancelar notas (Sem solicitação, com solicitação e estornar cancelamento)',
    'Substituir notas (Com solicitação e estornar substituição de nota fiscal)',
    'Manutenção de guias de pagamento (Vencimento das guias, cancelamentod as guias, integração das guias)',
    'Manutenções fiscais (Alteração de dedução fiscal e regime tributário, manutenção e remuneração de nota fiscal)',
    'Importação de arquivos (Optantes do simples nacional/SIMEI)',
    'Exportação de notas (Notas fiscais e TSE)',
    'Sincronizar cadastros',
    'Gerenciador de processos',
    'RELATÓRIOS',
    'Acessos (Acessos dos usuários, adesão ao sistema, denúncia fiscal e solicitação de acessos pendentes)',
    'Cadastrais (Bairros e usuários de prestadores)',
    'Créditos (Créditos tributários. extrato dos créditos tributários, créditos tributários por prestadores e créditos tributários por tomadores)',
    'Notas fiscais (Evolução das notas fiscais, maiores eminentes de notas fiscais, manutenções fiscais, notas fiscais, prestadores por notas, serviços prestados e substituições de notas fiscais)',
    'Pagamentos (Evolução da arrecadação, relação de pagamentos, e situação das guias de pagamentos)',
    'RPS (Autorização para impressão de RPS, RPS convertidos e não liberados e RPS convertidos fora do prazo)',
    'Serviços x CNAE',
    'Gerenciador de relatórios',
    'CONSULTAS',
    'Consulta geral',
    'Consultar notas',
    'Consultar lotes de RPS',
    'RPS convertidos fora do prazo',
    'Consultar créditos',
    'Consultar manutenção fiscal',
    'Consultar remunerações de nota fiscal',
    'Cobrança registrada',
    'Importação de nota nacional',
    'RESUMOS',
    'Estatísticos dos valores do ISS',
    'Notas emitidas',
    'GRÁFICOS',
    'Arrecadação por competência',
    'Notas fiscais por atividade',
    'Evolução das notas fiscais',
    'Notas fiscais emitidas por período',
    'Notas fiscais emitidas por prestador',
    'Notas fiscais emitidas por tomador',
    'ACESSOS',
    'Módulo contribuinte',
    'PRESTAÇÃO DE CONTAS',
    'Validar necessidade de campos relacionados às prestações de contas'
  ]),
  'Tributos (Cloud)': parseTasksIntoSections([
    'Módulo Imobiliário',
    'Validar Contribuintes',
    'Validar Econômico',
    'Validar Imóvel',
    'Créditos tributarios (Descrição, abreviatura, indexador, vincular com, transferência para dívida e receitas)',
    'Parcelas (Ano e crédito tributário)',
    'Moratórios (Tipo de lançamento, ano, crédito tributário e script)',
    'Compensatório (Tipo de lançamento, ano, crédito tributário e script)',
    'IPTU',
    'Tabelas de cálculo (Ano, descrição e origem dos campos)',
    'Cadastros gerais (Descrição, exibição, identificador, descrição da coluna e tipo)',
    'Planta de valores (Ano, nº do ato, distrito, bairro, logradouro, seção, face, inscrição imobiliária, indexador e valor do m²)',
    'Contribuintes (Dados pessoais e de endereço, documentos, campos adicionais e anexos)',
    'Construtoras (Descrição, número do CREA e data de registro)',
    'Imobiliárias (Nome e número do CRECI)',
    'Engenheiros/ Arquitetos (Nome, Nº dp CREA/ CAU e data de registro)',
    'Cartórios (Contribuinte e tipo)',
    'Agências (Número, dígito, nome, banco, CEP, município, logradouro, Nº, bairro)',
    'Bancos',
    'Indexadores (Descrição, sigla, tipo e movimentações)',
    'Limites de arrecadação (Topos de crédito, tipo de baixa, forma de pagamento, valor máximo de diferença, crédito)',
    'Convênios',
    'Documentos',
    'Imóveis',
    'Englobamento (Contribuinte, tipo de imóvel e filtros)',
    'Desmembramentos',
    'Remembramentos',
    'Geoprocessamento',
    'Obras',
    'Receita diversas (TIpo de serviço/crédito tributário, dados do serviço e lançamento)',
    'Requerimento/Manutenção de lançamento (Dados gerais, requerimento, receita de crédito e manutenção)',
    'Antecipação/Prorrogação de vencimentos (Definir filtros e prorrograr/antecipar vencimentos)',
    'Naturezas do texto jurídico (Descrição)',
    'Fontes de divulgação (Descrição e meio de comunicação)',
    'Atos',
    'Feriados (Descrição, abrangência, tipo e data)',
    'Unidades de medida (Símbolo, descrição singular, descrição plural, grandeza e gracionável?)',
    'Endereços (Faces, logradouros, condomínios, loteamentos, bairros, distritos, estados, municípios, seções e localidades)',
    'Benefícios fiscais (Descrição, tipo, ato/lei, validade e fundamentação legal)',
    'Motivos (Tipo, Lei/Ato e descrição)',
    'Materiais e serviços (Tipo, descrição, unidade de medida e tipo de cálculo)',
    'Guias (Tipo de lançamento, 2ª via?, crécdito tributário, convênio, data para pagamento, indexador, mostrar código de barras cobrar taxa de expediente?,)',
    'Transferência de imóveis (Informar dados, definir imóveis, configurar transferência e visualizar resumo)',
    'Não análisada',
    'Em análise',
    'Aguardando resposta',
    'Resposta recebida',
    'Deferida',
    'Indeferida',
    'Manutenção de pagamentos - pagamentos e saldos (Tipo de pagamento, tipo de inconsistência, nº do processo, observações, filtrar pagamento e gerar saldo)',
    'Cálculo (Ano e crédito tributário)',
    'Controle de saldo devedor',
    'Baixa automática/ estorno (Convênio, script, arquivo, baixa retroativa? data)',
    'Baixa manual/ estorno (Contribuinte, guia unificada, tipo de lançamento, exercício e Nº da parcela)',
    'Integração contábil (Validar integração no todo)',
    'Parcelamento de créditos (Dados gerais e filtros,  lançamentos a serem parcelados e confirmar parcelamento)',
    'Cancelamento/Reativação de documentos (Definir filtros e visualizar resultados)',
    'Encerramento',
    'Validar necessidade de campos relacionados às prestações de contas',
    'Módulo Dívida Ativa',
    'Parcelamento de créditos (Dados gerais, créditos tributários e taxas, parcelas)',
    'Documentos',
    'Agências (Número, dígito, nome, banco, CEP, município, logradouro, Nº, bairro)',
    'Bancos',
    'Indexadores (Descrição, sigla, tipo e movimentações)',
    'Limites de arrecadação (Topos de crédito, tipo de baixa, forma de pagamento, valor máximo de diferença, crédito)',
    'Convênios',
    'Receita diversas (TIpo de serviço/crédito tributário, dados do serviço e lançamento)',
    'Naturezas do texto jurídico (Descrição)',
    'Fontes de divulgação (Descrição e meio de comunicação)',
    'Atos',
    'Feriados (Descrição, abrangência, tipo e data)',
    'Unidades de medida (Símbolo, descrição singular, descrição plural, grandeza e gracionável?)',
    'Endereços (Faces, logradouros, condomínios, loteamentos, bairros, distritos, estados, municípios, seções e localidades)',
    'Motivos (Tipo, Lei/Ato e descrição)',
    'Benefícios fiscais (Descrição, tipo, Ato/Lei, validade e fundamentação legal)',
    'Materiais e serviços (Tipo, descrição, unidade de medida e tipo de cálculo)',
    'Guias (Tipo de lançamento, 2ª via?, crédito tributário, convênio, data para pagamento, indexador, mostrar código de barras?, cobrar taxa de expediente? e filtros)',
    'Livros de dívida ativa (Modelo e filtros)',
    'Termos de abertura/ encerramento do livro (Modelo e filtros)',
    'Baixa automática/ estorno - homologados e estornados (Convênio, script, arquivo baixa retroativa? e data)',
    'Baixa manual/ estorno (Contribuintes, guia unificada, tipo de lançamento, exercício e Nº da parcela)',
    'Integração contábil (Validar integração no todo)',
    'Inscrição em dívida (Débitos a serem inscritos e inscritos)',
    'Estorno de inscrição (Abertos e estornados)',
    'Parcelamento de créditos - Quitados e cancelados (Dados gerais e filtros,  lançamentos a serem parcelados e confirmar parcelamento)',
    'Anistias (Tipo, data, número do processo, fórmula, motivo, observações e filtros)',
    'Cancelamentos (Tipo, data, número do processo, fórmula, motivo, observações e filtros)',
    'Prescrições (Tipo, data, número do processo, fórmula, motivo, observações e filtros)',
    'Remissões (Tipo, data, número do processo, fórmula, motivo, observações e filtros)',
    'Suspensões (Tipo, data, número do processo, fórmula, motivo, observações e filtros)',
    'Prestações diversas (Tipo, data, número do processo, fórmula, motivo, observações e filtros)',
    'Transferência de dívida (Validar dívidas transferidas e processo de transferência)',
    'Cancelamento/ reativação de documentos  (Status, natureza, Nº do documento, modelo e contribuintes)',
    'Encerramento',
    'Validar necessidade de campos relacionados às prestações de contas',
    'Módulo Mobiliário',
    'TABELAS',
    'BASE CADASTRAL',
    'PESSOAS',
    'LANÇAMENTOS',
    'DOCUMENTOS',
    'FINANCEIRO',
    'Bancos',
    'TAXAS',
    'EMPRESAS',
    'CADASTROS AUXILIARES',
    'EMISSÃO',
    'CONSULTAS',
    'MOVIMENTAÇÃO FINANCEIRA',
    'MANUTENÇÕES',
    'ENCERRAMENTO MENSAL',
    'PRESTAÇÃO DE CONTAS'
  ]),
  'Procuradoria (Cloud)': parseTasksIntoSections([
    'AGENDA',
    'Validar funcionabilidade da agenda',
    'PESSOAS',
    'Contribuintes (Dados pessoais, dados de endereço, documentos e anexos)',
    'Referentes (Tipo, código, contribuinte, logradouro, número, bairro, município, corresponsável, proprietários, quadra, lote, inscrição imobiliária e complemento)',
    'Cartórios (Nome e tipo)',
    'Advogados e procuradores (Tipo, nome, inscrição na OAB, seccional OAB, complemento OAB e usuário)',
    'FINANCEIRO',
    'Agências (Número, dígito, nome, banco, CEP, município, logradouro, Nº, bairro)',
    'Bancos',
    'Convênios (Descrição, número, banco, agência, fórmula, modelo de carne, conta bancária. créditos tributarios, pode utilizar em parcelamentos? usa validade para número de baixa?, validade do número de baixa. homologar baixa e mensagens)',
    'Créditos tributários',
    'CADASTROS AUXILIARES',
    'Endereços (Faces, logradouros, condomínios, loteamentos, bairros, distritos, estados, municípios, seções e localidades)',
    'Áreas e assuntos (Código e descrição)',
    'Locais de tramitação (Tribunal)',
    'Grupos de trabalho (Descrição do grupo, data de ativação, áreas e pessoas que fazem parte do grupo)',
    'Classes (Código e descrição)',
    'Motivos (Descrição e tipo)',
    'CONTROLE DE DOCUMENTOS',
    'Cancelamento/ Reativação de documentos (Validar documentos ativos e cancelados)',
    'Modelos de petições intermediárias (Validar petições)',
    'Documentos emitidos (Certidão de dívida ativa, petição inicial e petição intermediária)',
    'DÍVIDAS',
    'Dívidas ativas (Sem certidão, com certidão, com petição,  protestada, protestada com petição, executada, executada e protestada)',
    'Processos  (execuções fiscais. quitadas/canceladas, parceladas/ suspensas e suspensas com dívidas em aberto)',
    'GERENCIADOR DE PROTESTOS',
    'Protestos (protestos, quitadas/ canceladas, parceladas/ suspensas)',
    'Validar necessidade de campos relacionados às prestações de contas',
    'EMISSÃO',
    'CONSULTAS',
    'MOVIMENTAÇÃO FINANCEIRA',
    'MANUTENÇÕES',
    'ENCERRAMENTO MENSAL',
    'PRESTAÇÃO DE CONTAS'
  ]),
  'Livro Eletrônico': parseTasksIntoSections([
    'CADASTROS',
    'Entidade',
    'Configurações (Gerais, fórmulas, autos de infrações, notas avulsas, certidão negativa, solicitações de acesso, configurações auxiliares e integrações)',
    'Pessoa',
    'Contribuintes',
    'Contadores',
    'Gráficas',
    'Financeiros (Competências, convênios, indexadores, feriados e incentivos fiscais)',
    'Base cadastral (Lista de serviços da lei 116/03, alíquotas do simples nacional, faixas do IRRF, plano de contas, despesas, materiais, taxas diversas, motivos da alteração de alíquota, entidades especiais, intes de ISS fixo e séries)',
    'Auto de infração (Infrações e autos de infrações)',
    'Endereços (Bairros, condemínios, logradouros e loteamentos)',
    'Fiscalizações por período',
    'PROCESSOS',
    'Liberação de acesso',
    'AIDF (Liberação de AIDF e Validação de recibos de AIDF)',
    'Contador (Desvínculo de contador e transferência de contador)',
    'Notas Avulsas',
    'Guias Tributos Cloud',
    'Saldos (Consultar saldos, lançar saldos, liberar saldos bloqueados, bloquear saldos liberados, cancelar saldos e utilizar saldos por restituição)',
    'Encerramento de declarações',
    'Reabertura das declarações (Serviços e despesas)',
    'Análise das declarações  (Gerenciados de pendências e cruzamento de documentos)',
    'Alteração cadastral',
    'Sincronizar dados',
    'Gerenciador de processos',
    'RELATÓRIOS',
    'Movimentação cadastral (Contribuintes e plano de contas)',
    'Movimentação fiscal',
    'Análise dos documentos',
    'Análise dos documentos importados',
    'Serviços prestados não declarados pelo tomador',
    'Serviços prestados por município',
    'Serviços tomados não declarados pelo prestador',
    'Serviços tomados por município',
    'Situação dos contribuintes',
    'Encerramento simples nacional',
    'Taxas diversas',
    'Cruzamento entre declarações dos serviços e dos valores recebidos em cartão',
    'Movimentação financeira (Arrecadações de ISS, lançamentos de ISS, arrecadações e lançamentos de ISS, maiores prestadores, maiores tomadores, maiores atividades, situação das guias de pagamento, guias registradas e maiores contribuintes por condições em cartão)',
    'Contador (Certidão de desvínculo de contador, comprovante de transferência de contador, contribuintes por contador e transferências de contador)',
    'Conferência do livro do ISS',
    'Recibo de ISS retido/por substituição',
    'Recibos de declarações',
    'Fiscalização por período',
    'AIDF (Documentos fiscais liberados e não declarados, documentos fiscais não autorizados e relatório de AIDF)',
    'Gerenciador de relatórios',
    'CONSULTAS',
    'Cobrança registrada',
    'ACESSO',
    'Módulo contribuinte',
    'PRESTAÇÃO DE CONTAS',
    'Validar necessidade de campos relacionados às prestações de contas',
    'EMISSÃO',
    'CONSULTAS',
    'MOVIMENTAÇÃO FINANCEIRA',
    'MANUTENÇÕES',
    'ENCERRAMENTO MENSAL',
    'PRESTAÇÃO DE CONTAS'
  ]),
  'Protocolo (Cloud)': parseTasksIntoSections([
    'PESSOAS',
    'Nome',
    'CPF/CNPJ',
    'Nome Social',
    'Endereços',
    'Telefone',
    'E-mail',
    'Filiações',
    'Estado Civil',
    'Sexo',
    'Data de nascimento',
    'Data de óbito',
    'ORGANOGRAMAS',
    'Configuração de organograma',
    'Usuários/Responsáveis do organograma',
    'ENDEREÇOS',
    'Países',
    'Estados',
    'Municipios',
    'Bairros',
    'Tipo de logradouro',
    'Logradouros',
    'Condominio',
    'CEP do logradouro',
    'Bairro do logradouro',
    'GESTÃO DE PROCESSOS',
    'Processo',
    'Confirmações',
    'Andamentos',
    'Transferências',
    'Estorno de processos',
    'Localização do processo (processo-organograma-usuario)',
    'Processo-Volume',
    'Movimentações',
    'Classificação',
    'Arquivamentos',
    'Processo Organograma',
    'Partes interessadas do processo',
    'Geolocalização',
    'Juntamentos de processos',
    'Guias de pagamento',
    'Parecer',
    'Deferidos',
    'Indeferido',
    'Confirmado',
    'Anulado',
    'Conhecimento',
    'Parcial',
    'Outros',
    'ASSUNTOS',
    'Validar informações adicionais',
    'Configurações do Assunto',
    'Documentos do assunto',
    'Guias de pagamento',
    'Taxas do assunto',
    'EMISSÃO',
    'CONSULTAS',
    'MOVIMENTAÇÃO FINANCEIRA',
    'MANUTENÇÕES',
    'ENCERRAMENTO MENSAL',
    'PRESTAÇÃO DE CONTAS'
  ]),
  'Portal Gestor (Cloud)': parseTasksIntoSections([
    'CONTÁBIL',
    'Configurações gerais',
    'Cargas',
    'Índices',
    'ARRECADAÇÃO',
    'Configurações gerais',
    'Cargas',
    'Índices',
    'Configurações gerais',
    'Cargas',
    'Índices',
    'PESSOAL',
    'Configurações gerais',
    'Cargas',
    'Índices',
    'SAÚDE',
    'Configurações gerais',
    'Cargas',
    'Índices',
    'EDUCAÇÃO',
    'Configurações gerais',
    'Cargas',
    'Índices',
    'CONTRATOS',
    'Configurações gerais',
    'Cargas',
    'Índices',
    'Processo-Volume',
    'Movimentações',
    'Classificação',
    'Arquivamentos',
    'Processo Organograma',
    'Partes interessadas do processo',
    'Geolocalização',
    'Juntamentos de processos',
    'Guias de pagamento',
    'Deferidos',
    'Indeferido',
    'Confirmado',
    'Anulado',
    'Conhecimento',
    'Parcial',
    'Outros',
    'Validar informações adicionais',
    'Configurações do Assunto',
    'Documentos do assunto',
    'Guias de pagamento',
    'Taxas do assunto',
    'EMISSÃO',
    'CONSULTAS',
    'MOVIMENTAÇÃO FINANCEIRA',
    'MANUTENÇÕES',
    'ENCERRAMENTO MENSAL',
    'PRESTAÇÃO DE CONTAS'
  ]),
  'Contábil (Cloud)': parseTasksIntoSections([
    'PARÂMETROS GERAIS',
    'Parâmetros (Efetivar retenção, Ordem de baixa)',
    'Portal da transparência fly (Informações Gerais, Envio de Relatórios)',
    'Portal da transparência cloud (Informações Gerais, Envio de Relatórios)',
    'EFD-Reinf (É ente federativo responsável?, Entidade beneficiente/isenta de contribuições sociais, Responsável pelas informações EFD-Reinf, Chave de Acesso, Script)',
    'ESCRITURAÇÃO',
    'Plano de contas (Configuração, Máscara,Tipo,Vigência,Descrição,Função)',
    'Eventos contábeis (Número, Vigência, Título, Documento, Abrangência,Aplicabilidade,Condição,Histórico,Histórico de Estorno)',
    'Regras de documentos (Descrição, Status, Documento)',
    'Contas Correntes (Descrição, Lote, Vigência, Condição, Componentes)',
    'Componentes (Descrição, Configuração, Fonte de Dados, Campo, Filtro, Documentos)',
    'Equivalências (Conta Contábil, Classificação)',
    'Itens de equivalência (Descrição, Documento, Campo, Item)',
    'Processos (Configuração, Descrição, Tipo, Script)',
    'FUNCIONAL PROGRAMÁTICA',
    'Programas (Programa, Público-Alvo, Objetivos do Programa)',
    'Configuração de Funcionais (Configuração, Número, Descrição)',
    'Ações (Ação, Tipo, Descrição, Finalidade)',
    'PESSOAS',
    'Assinantes (Nome, CPF, Função, Complemento)',
    'Credores (Informações Gerais, Campos Adicionais)',
    'Ordenadores de Despesa (Informações Gerais, Campos Adicionais)',
    'Responsáveis (Informações Gerais, Campos Adicionais)',
    'ASSINATURAS',
    'Assinaturas (Data inicial, data final, grupo, organograma, assinantes e campos adicionais)',
    'ATOS',
    'Tipos de Atos (Informações Gerais, Campos Adicionais)',
    'Atos (Número, Tipo, Natureza do texto jurídico, Data de criação, Data a vigorar, Data da revogação, Data da sanção, Data de publicação, Número do diário oficial, Fontes de divulgação e Ementa)',
    'Naturezas de Texto Jurídico (Informações Gerais, Campos Adicionais)',
    'Fontes de divulgação (Nome e meio de comunicação)',
    'ESTRUTURA ORGANIZACIONAL',
    'Organogramas (Configuração, Número, Descrição, Tipo de Administração, Campos Adicionais)',
    'Entidade (Informações Gerais, Campos Adicionais)',
    'NATUREZAS',
    'Receitas (Configuração, Informações Gerais, Campos Adicionais)',
    'Despesas (Configuração, Informações Gerais, Campos Adicionais)',
    'CONTROLE',
    'Localizadores (Descrição)',
    'Recursos (Configuração, Informações Gerais, Campos Adicionais)',
    'Retenções (Informações Gerais, Campos Adicionais)',
    'Receitas Extraorçamentárias (Informações Gerais, Campos Adicionais)',
    'Comprovantes (Informações Gerais, Campos Adicionais)',
    'Diárias (Informações Gerais, Campos Adicionais)',
    'BANCÁRIOS',
    'Agências bancárias (Informações Gerais, Campos Adicionais)',
    'Contas bancárias (Informações Gerais, Campos Adicionais)',
    'CADASTROS AUXILIARES',
    'Adicionando projeção atuarial previdenciária (Informações Gerais, Campos Adicionais)',
    'Adicionando projeção atuarial plano financeiro (Informações Gerais, Campos Adicionais)',
    'Unidades de medida (Informações Gerais, Campos Adicionais)',
    'Origens de alterações de despesas (Informações Gerais, Campos Adicionais)',
    'Tipos de comprovante (Informações Gerais, Campos Adicionais)',
    'Deduções das receitas (Informações Gerais, Campos Adicionais)',
    'Endereços (Logradouros, Condomínios, Loteamentos, Bairros, Distritos, Estados, Municípios)',
    'Tipos de Dívida (Informações Gerais, Campos Adicionais)',
    'Tipos de Precatórios (Informações Gerais, Campos Adicionais)',
    'Tipos de Responsáveis (Informações Gerais, Campos Adicionais)',
    'Tipos de Administração (Informações Gerais, Campos Adicionais)',
    'Tipos de alteração de receita (Informações Gerais, Campos Adicionais)',
    'Transações financeiras (Informações Gerais, Campos Adicionais)',
    'Tipos de bloqueios (Informações Gerais, Campos Adicionais)',
    'Tipos de aplicação (Informações Gerais, Campos Adicionais)',
    'Despesas não previstas na LOA (Informações Gerais, Campos Adicionais)',
    'Receitas não previstas na LOA (Informações Gerais, Campos Adicionais)',
    'Desmembramento de receitas (Informações Gerais, Campos Adicionais)',
    'Saldos iniciais extraorçamentários (Informações Gerais, Campos Adicionais)',
    'RECEITA',
    'Arrecadações (Informações Gerais, Campos Adicionais)',
    'Arrecadações Extras Orçamentárias (Informações Gerais, Campos Adicionais)',
    'Lançamentos de receita (Data, Receita, Valor, Descrição)',
    'Devoluções de receita (Número, Data, Dedução, Valor, Credor, Conta Bancária Credor, Finalidade, Receita, Valor, Data de vencimento, Baixa)',
    'Alteração orçamentária da receita (Informações Gerais, Campos Adicionais)',
    'CONTROLE',
    'Prestação de contas - Adiantamentos e diárias',
    'Dívidas (Informações Gerais, Campos Adicionais)',
    'Contratos de Rateio (Informações Gerais, Campos Adicionais)',
    'Prestação de contas de consórcio (Número, Consórcio, Contrato, Recurso, Função, Subfunção, Natureza da despesa)',
    'INTERAÇÕES',
    'Gerenciador de integrações',
    'DESPESA',
    'Empenhos (Informações Gerais, Campos Adicionais)',
    'Liquidações (Informações Gerais, Campos Adicionais)',
    'Pagamentos (Informações Gerais, Campos Adicionais)',
    'Despesa Extra (Informações Gerais, Campos Adicionais)',
    'Alterações orçamentárias da despesa (Informações Gerais, Campos Adicionais)',
    'Bloqueios/Desbloqueios da despesa (Informações Gerais, Campos Adicionais)',
    'PROGRAMAÇÃO FINANCEIRA',
    'Programação financeira da receita',
    'Programação financeira da despesa',
    'PERÍODO FINANCEIRO',
    'Período financeiro (Abertura, Encerramento, Configuração)',
    'ESCRITURANDO',
    'Escriturações de documentos (Informações Gerais, Campos Adicionais)',
    'Balancete dinâmico',
    'Períodos da escrituração (Abertura, Encerramento, Configuração)',
    'PRESTAÇÃO DE CONTAS',
    'Validar necessidade de campos relacionados às prestações de contas'
  ]),
  'Planejamento (Cloud)': parseTasksIntoSections([
    'PLANEJAMENTO',
    'PPA (Composição da receita e despesa, Composição da receita, Composição da despesa)',
    'LDO (Composição da receita e despesa, Composição da receita, Composição da despesa e Nível da natureza da despesa)',
    'LOA (Composição da receita, Nível da natureza da despesa, Gerar número reduzido para "receitas e despesas")',
    'ESCRITURAÇÃO',
    'FUNCIONAL PROGRAMÁTICA',
    'FUNCIONAL PROGRAMÁTICA',
    'PPA (Receitas, Despesas, Programas, Ações, Organogramas e Recursos)',
    'LDO (Receitas, despesas, programas, ações, organogramas, recursos, transferências financeiras, cernários macroeconômicos e limites)',
    'LOA (Receitas, despesas, programas, ações, organogramas, recursos, transferências financeiras e limites)',
    'Função (número e descrição)',
    'Subfunções (número e descrição)',
    'PPA (Receitas, Despesas, Programas, Ações, Organogramas e Recursos)',
    'LDO (Receitas, despesas, programas, ações, organogramas, recursos, transferências financeiras, cernários macroeconômicos e limites)',
    'LOA (Receitas, despesas, programas, ações, organogramas, recursos, transferências financeiras e limites)',
    'Atuários (Nome, CPF/CNPJ, Registro do IBA, Endereços e Campos Adicionais)',
    'PESSOAS',
    'Assinantes (Nome, CPF, Função e Complemento)',
    'Responsáveis (Nome, CPF, Descrição do cargo, Tipo, Endereço, Telefone, E-mails, Registro, RG, Anexos e Campos adicionais)',
    'ASSINATURAS',
    'Assinaturas (Data inicial, Data final, Grupo, Organograma(s) e Assinantes)',
    'Grupo de configuração de assinaturas (Descrição)',
    'INDICADORES',
    'Indicadores (Descrição e campos adicionais)',
    'Indicadores de programas (Programa, indicador, unidade de medida, índice de referência, data de apuração, fonte, observações, índices esperados e campos adicionais)',
    'ESTRUTURA ORGANIZACIONAL',
    'Organogramas (Número, descrição e tipo de administração)',
    'Entidades (Dados cadastrais da entidade)',
    'BASE ESTRATÉGICA',
    'Equipes de planejamento (Descrição, ato de nomeação, período e atribuições)',
    'Audiências (Tema, ato, data e hora, primeira convocação, situação, equipe de planejamento, endereços beneficiados, tipo de audiência, endereço da audiência, assunto e campos adicionais)',
    'Orientações estratégicas (Denominação, Equipe de planejamento, Data, Situação, Orientação e Justificativa)',
    'Sugestões (Origem, Tipo, Data, Categoria, Endereço beneficiado, Assunto, Sugestão apresentada), avaliar as sugestões em avaliação, viabilidade e concluidas.',
    'Macro-objetivos (Denominação e Descrição)',
    'Objetivos estratégicos (Objetivo, Macro objetivos e Definição do objetivo)',
    'CADASTROS AUXILIARES',
    'ATOS',
    'ATOS',
    'Tipos de atos (Descrição e Classificação)',
    'Atos (Número, Tipo, Natureza do texto jurídico, Data de criação, Data a vigorar, Data da revogação, Data da sanção, Data de publicação, Número do diário oficial, Fontes de divulgação e Ementa)',
    'Natureza de texto jurídico (Descrição e campos adicionais)',
    'Fontes de divulgação (Nome e meio de comunicação)',
    'PPA (Receitas, Despesas, Programas, Ações, Organogramas e Recursos)',
    'LDO (Receitas, despesas, programas, ações, organogramas, recursos, transferências financeiras, cernários macroeconômicos e limites)',
    'LOA (Receitas, despesas, programas, ações, organogramas, recursos, transferências financeiras e limites)',
    'Recursos (Número, Tipo, Descrição, Marcadores e Campos adicionais)',
    'NATUREZAS',
    'Receita (Número, tipo, descrição, marcadores e campos adicionais)',
    'Despesa (Número, tipo, descrição, marcadores e campos adicionais)',
    'CADASTROS AUXILIARES',
    'Unidades de medida (Abreviatura e descrição)',
    'Origens de alterações de despesa (Descrição e enquadramento legal)',
    'Deduções da receita (Descrição e tipo)',
    'Endereços (Informações cadastrais de Logradouros, Condomínios, Bairros, Distritos, Estados e Municípios)',
    'Tipos de compensações (Descrição)',
    'Tipos de renúncias físicas (Descrição)',
    'Tipos de administração (Descrição, natureza jurídica, tipo de administração e poder)',
    'Tipos de alteração de receita (Descrição e tipo)',
    'Tipos de resultados nominais (Descrição)',
    'Tipos de riscos fiscais (Descrição e classificação na LRF)',
    'Tipos de responsáveis (Descrição)',
    'Despesas não previstas na LOA',
    'Marcadores (Descrição e lote)',
    'Em elaboração (Número, data, crédito, despesa, tipo de crédito, finalidade, anexos e campos adicionais)',
    'Anulada (Número, data, crédito, despesa, tipo de crédito, finalidade, anexos e campos adicionais)',
    'Sancionada (Número, data, crédito, despesa, tipo de crédito, finalidade, anexos e campos adicionais)',
    'Em tramitação de alteração orçamentaria (Número, data, crédito, despesa, tipo de crédito, finalidade, anexos e campos adicionais)',
    'Enviada p/ alteração orçamentária (Número, data, crédito, despesa, tipo de crédito, finalidade, anexos e campos adicionais)',
    'Limites das despesas da LOA (Número, valor, itens e motivo)',
    'PPA',
    'Receitas (Natureza da receita, entidade, meta financeira quadrienal, meta financeira anual, deduções, marcadores e campos adicionais)',
    'Despesas (Entidade, organograma, programa, ação, função, subfunção, meta financeira quadrienal, meta financeira anual, metas físicas, marcadores e campos adicionais)',
    'Execução das metas físicas',
    'Avaliação do PPA (Exercício, equipe de planejamento, avaliação da gestão do plano e campos adicionais)',
    'LDO',
    'Receitas (Natureza da receita, entidade, meta financeira, deduções, marcadores e campos adicionais)',
    'Despesas (Entidade, organograma, programa, ação, função, subfunção, meta financeira, metas físicas, marcadores e campos adicionais)',
    'Expansão de despesas (Despesa, descrição, atos, valor, projeção 2030, projeção 2031)',
    'Projeções atuariais previdenciárias (Atuário. registro do IBA, data base de cálculo e saldo financeiro em 2025)',
    'Projeções atuariais plano financeiro (Atuário. registro do IBA, data base de cálculo e saldo financeiro em 2025)',
    'Resultados nominais (Tipo resultado, exercícioatual, anos anteriores e próximos anos)',
    'Riscos Fiscais (Tipo, entidade, organograma, detalhamento, providência, exercício atual, próximos anos)',
    'Renúncias físicas (Receita, tipo, localizador, ato regulamentar,  descrição, exercício atual, próximos anos)',
    'Metas fiscais da receita',
    'Metas fiscais da despesa',
    'Transferências financeiras (Entidade, organograma (origem). Destino, entidade, organograma, recurso, finalidade e valor (destino).',
    'LOA',
    'Receitas (Natureza da receita, entidade,  organograma, meta financeira, especificação, recursos, deduções, marcadores e campos adicionais)',
    'Despesas (Entidade, organograma, programa, ação, função, subfunção, meta financeira, metas físicas e campos adicionais)',
    'Transferências financeiras (Entidade, organograma (origem). Destino, entidade, organograma, recurso, finalidade e valor (destino).',
    'Alterações orçamentárias da receita (Tipo de alteração, finalidade, receita, impacto da alteração e valor)',
    'Alterações orçamentárias da despesa',
    'Créditos em elaboração (Crédito, despesa, tipo de crédito, finalidade e campos adicionais)',
    'Propostas (Crédito, despesa, tipo de crédito, finalidade e campos adicionais)',
    'No legislativo (Crédito, despesa, tipo de crédito, finalidade e campos adicionais)',
    'Sancionada (Crédito, despesa, tipo de crédito, finalidade e campos adicionais)',
    'Solicitações de despesas',
    'Limites na LOA',
    'Manutenção',
    'Programação financeira da receita',
    'Programação financeira da despesa',
    'PROCESSOS',
    'Cópia de PPA',
    'Relatório da cópia de PPA',
    'Cópia do LDO',
    'Relatório da cópia de LDO',
    'PRESTAÇÃO DE CONTAS',
    'PRESTAÇÃO DE CONTAS'
  ]),
  'Tesouraria (Cloud)': parseTasksIntoSections([
    'PARÂMETROS GERAIS',
    'Parâmetros (Reconhecer documento, controlar movimentação diária)',
    'Movimentos (Data, observação e campos adicionais)',
    'Remessas bancárias (Descrição, script, banco e campos adicionais)',
    'Critérios de conciliação (Descrição)',
    'Portal da transparência fly (Chave de aceesso, e-mail de retorno, exercício do primeiro envio, data e hora do último envio, script)',
    'IMPLANTAÇÃO',
    'Parâmetros da implantação (Data da implantação)',
    'Saldo inicial em dinheiro (Data, valor, finalidade e recursos)',
    'BANCÁRIOS',
    'Agências (Banco, nome da agência, número, dígito, CEP, logradouro, número, bairro, município e campos adicionais)',
    'Contas (Banco, marcadores, anexos e campos adicionais)',
    'Cheques (Conta bancária, número inicial, número final, quantidade, observação e campos adicionais)',
    'CONTROLE',
    'Recursos (Número, tipo, descrição, recurso de superávit financeiro, marcadores e campos adicionais)',
    'Retenções (Descrição, tipo, credores, naturezas da despesa e campos adicionais)',
    'Receitas extraorçamentárias (Descrição, tipo, recursos e campos adicionais)',
    'PESSOAS',
    'Assinantes (Nome, CPF, função e complemento)',
    'Credores (Nome, CPF/CNPJ, data de inclusão, dados pessoais, documentos, contas bancárias. EFD-REINF)',
    'Responsáveis (Nome, CPF, descrição do cargo, tipo, dados pessoaism anexos e campos adicionais)',
    'ESTRUTURA ORGANIZACIONAL',
    'Organogramas (Número, Descrição, Tipo de Administração e Campos Adicionais)',
    'Entidade (Informações Gerais e Campos Adicionais)',
    'ASSINATURAS',
    'Assinaturas (Data inicial, data final, grupo, organograma, assinantes e campos adicionais)',
    'Grupo de configuração de assinaturas (Descrição)',
    'CADASTROS AUXILIARES',
    'Deduções da receita (Descrição, tipo e campos adicionais)',
    'Tipos de movimentos (Descrição, tipo e campos adicionais)',
    'Tipos de aplicação (Descrição e campos adicionais)',
    'Tipos de documentos (Descrição e campos adicionais)',
    'Tipos de administração (Descrição, natureza jurídica, tipo de administração, poder e campos adicionais)',
    'Tipos de responsáveis (Descrição e campos adicionais)',
    'Transações financeiras (Descrição, tipo e campos adicionais)',
    'Endereços (Informações cadastrais de Logradouros, Condomínios, Bairros, Distritos, Estados e Municípios)',
    'PROCESSOS',
    'Arrecadações (Data, transação, número do documento, valor, conta bancária, tipo de conta, especificação, campos adicionais e pendências)',
    'Pagamentos',
    'A pagar (Empenho, subempenho, despesa extra e devolução receita)',
    'Pago (Empenho, subempenho, despesa extra e devolução receita)',
    'Devoluções da receita (Número, data, dedução, valor, credor, conta bancária credor, finalidade, receita, valor, data de vencimento)',
    'Ajustes de recursos (Data, categoria, valor, recurso de origem, recurso de destino e finalidade)',
    'BANCÁRIOS',
    'Gestão (Aplicação e Configuração de emissão)',
    'Conciliações (Conta bancária, tipo de conta, período, saldo financeiro, saldo do extrado, saldo a conciliar, data conclusão, pendência, anexos e campos adicionais)',
    'Transferências (Número, data, conta bancária origem, tipo conta origem, recurso, valor, conta bancária destino, tipo conta destino, finalidde, data de vencimento, baixa e campos adicionais)',
    'PRESTAÇÃO DE CONTAS',
    'Validar necessidade de campos relacionados às prestações de contas'
  ]),
  'Convênios (Cloud)': parseTasksIntoSections([
    'ATOS',
    'Tipos de Atos (Descrição, classificação e campos adicionais)',
    'Atos (Número, Tipo, Natureza do texto jurídico, Data de criação, Data a vigorar, Data da revogação, Data da sanção, Data de publicação, Número do diário oficial, Fontes de divulgação e Ementa)',
    'Naturezas de Texto Jurídico (Descrição e campos Adicionais)',
    'Fontes de divulgação (Nome e meio de comunicação)',
    'PARTICIPANTES',
    'Concedentes (Nome, CPF/CNPJ e esfera administrativa)',
    'Convenentes (Nome e CPF/CNPJ)',
    'Certidões de convenentes (Convenente, número, tipo, data de emissão e data de validade)',
    'Certidões da entidade (Número, tipo, data de emissão, data de validade e campos adicionais)',
    'CONTROLE',
    'Comprovantes (Tipo do comprovante, Nº do comprovante, Data de emissão, série do comprovante, código de validação do comprovante, convenente, valor brut, valor do desconto, valor líquido e finalidade)',
    'ESTRUTURA ORGANIZACIONAL',
    'Entidades (Informações gerais e campos adicionais)',
    'CADASTROS AUXILIARES',
    'Modalidades (Descrição)',
    'Responsáveis (Nome, CPF, tipo e campos adicionais)',
    'Tipos de certidões (Descrição)',
    'Tipos de comprovantes (Descrição e tipo)',
    'Tipos de aditivos (Descrição, classificação e tipo)',
    'Tipos de situação (Descrição)',
    'Tipos de repasses (Descrição e classificação)',
    'Tipos de responsáveis (Descrição)',
    'CONVÊNIOS',
    'Recebidos (Número, valor do repasse, valor de contrapartida, valor global, objeto, período, data da assinatura, conta bancária, modalidade, concedente, ato autorizativo, certidões, responsáveis, anexos e campos adicionais). Validar os em prestação e os concluidos.',
    'Repassados',
    'Convênio (Número, Valor repassado, valor de contrapartida, valor global, objeto, período, data da assinatura, tipo, modalidade, conta bancária, convenente, ato autorizativo, certidões, responsáveis, anexos e campos adicionais)',
    'Formalização e execução (Convênios e aditivos)',
    'Prestação de contas (A comprovar, em comprovação e comprovado)',
    'Concluído (Convenios e aditivos)',
    'PRESTAÇÃO DE CONTAS',
    'Validar necessidade de campos relacionados às prestações de contas'
  ]),
  'Folha (Cloud)': parseTasksIntoSections([
    'CADASTRO DE ENTIDADE',
    'Tipo de administração',
    'Poder/Órgão público',
    'Valor do teto remuneratório',
    'Situação da entidade',
    'Natureza Jurídica',
    'Classificação tributária',
    'Tributação de PIS e COFINS',
    'Registro eletrônico de funcionário',
    'Entidade educacional',
    'Ente federativo responsável',
    'Unidade Gestora de RPPS',
    'Possui previdência complementar',
    'Informações da guia \'Contato\'',
    'Informações da guia \'Responsáveis\'',
    'Verificar se há campos adicionais',
    'CADASTRO DE GRUPOS FUNCIONAIS',
    'Quantidade',
    'Descrição',
    'Verificar se o cliente controla grupo funcional por código',
    'CADASTRO DE ORGANOGRAMAS',
    'Conferir a configuração do organograma',
    'Conferir a quantidade de organogramas',
    'Conferir código dos organogramas',
    'Conferir descrição dos organogramas',
    'Conferir se há campos adicionais',
    'CADASTRO DE LOTAÇÕES FÍSICAS',
    'Conferir a configuração de lotações físicas',
    'Conferir a quantidade de lotações físicas',
    'Conferir código das lotações físicas',
    'Conferir descrição das lotações físicas',
    'Conferir se há campos adicionais',
    'CADASTRO DE ATOS',
    'Conferir quantidade de atos',
    'Conferir tipos de atos',
    'Conferir natureza dos textos jurídicos',
    'Conferir as datas dos atos',
    'Verificar se há documentos anexos (pdf, imagens, etc)',
    'Conferir se há campos adicionais',
    'CADASTRO DE QUADRO DE CARGOS',
    'Verificar se há cadastro de quadro de vagas',
    'Quantidade de cadastros',
    'CADASTRO DE CARGOS',
    'Quantidade de cargos cadastrados',
    'Conferir CBO do cargo',
    'Verificar se há historico de cargos',
    'Verificar se há atos vinculados aos cargos',
    'Verificar descrição de cargo',
    'Verificar se o cliente controla cargo por código',
    'Verificar tipo de cargo',
    'Verificar se paga 13º salário',
    'Acúmulo de cargo',
    'Dedicação exclusiva',
    'Contagem especial',
    'Verificar se a quantidade de vagas de cada cargo está correta',
    'Verificar se há áreas de atuação vinculadas ao cargo e se a quantidade de vagas está correta',
    'Verificar se há organogramas vinculados ao cargo e se a quantidade de vagas está correta',
    'Verificar se há níveis salariais vinculados aos cargos e se os mesmos estão corretos',
    'Verificar se há vínculos empregatícios vinculados aos cargos',
    'Verificar se há cargos extintos',
    'Verificar se as datas de criação, extinção estão conforme ato informado',
    'Verificar se há Cursos exigidos, Requisitos e Atividades dos cargos',
    'Verificar se há campos adicionais',
    'CADASTRO DE ÁREAS DE ATUAÇÃO',
    'Verificar quantidade',
    'Descrição',
    'Verificar se cliente controla código da área de atuação',
    'Verificar se há Cursos , Requisitos e Atividades',
    'CBO',
    'Se há campos adicionais',
    'CADASTRO DE PLANOS DE CARGOS E SALÁRIOS',
    'Verificar quantidade',
    'Descrição',
    'Se controla carga horária nos níveis salariais',
    'Quando inicia (Data de admissão ou data base)',
    'Máscara da classe e referência',
    'Quais são as faixas de progressão',
    'Se existe algum afastamento que atrasa a progressão',
    'Quantos dias de afastamento são considerados para o atraso da progressão',
    'Quantos dias são atrasados',
    'CADASTRO DE NÍVEIS SALARIAIS',
    'Quantidade',
    'Descrição',
    'Verificar se cliente controla código do nível salarial',
    'Verificar data da vigência',
    'Valor inicial do nível',
    'Carga horária do nível',
    'Verificar se o plano informado está correto',
    'Verificar as classes e referências',
    'Verificar os valores das classes e referências',
    'Verificar se há campos adicionais',
    'CADASTRO DE MANUTENÇÃO DE ESTABELECIMENTOS',
    'Verificar se possui histórico das tabelas de todas as competências',
    'Verificar vigências',
    'Verificar percentuais informados em INSS do empregador',
    'Verificar os percentuais de RAT e FAP',
    'Verificar CNAE',
    'Verificar Código de GPS e percentuais  dos Transportadores e Obras',
    'Verificar opção de registro de ponto',
    'Verificar campos relacionados a PCD da guia Dados Processuais',
    'Verificar campos relacionados a Menor Aprendiz da guia Dados Processuais',
    'Verificar percentuais de RPPS',
    'Verificar percentuais de RGPS',
    'Verificar percentuais de IRRF',
    'Verificar informações de FGTS',
    'Verificar tipos e faixas do Salário Família',
    'CADASTRO DE TIPOS DE BASES',
    'Verificar se há informações cadastradas',
    'CADASTRO DE EVENTOS',
    'Verificar quantidade',
    'Verificar descrição',
    'Verificar tipo (Vencimento, desconto, informativo + ou informativo -',
    'Verificar natureza da rubrica',
    'Verificar classificação',
    'Verificar unidade',
    'Verificar taxa',
    'Verificar se envia para o eSocial',
    'Verificar código eSocial',
    'Verificar tabela de rubricas',
    'Verificar se é teto remuneratório',
    'Verficiar se envia para o transparência e se possui agrupador',
    'Verificar se possui configuração de baixa de provisão',
    'Verificar se possui em quais processamentos serão calculados',
    'Verificar se possui os motivos de rescisões que serão calculados',
    'Verificar se possui dedução de previdência',
    'Verificar se compõe as horas do mês',
    'Verificar se Inside DSR',
    'Verificar se possui informado que é para calcular por último',
    'Verificar se envia para a Rais',
    'Verificar incidencias (eSocial)',
    'Verificar se há campos adicionais',
    'Verificar se veio as fórmulas padrões',
    'CADASTRO DE MÉDIAS E VANTAGENS',
    'Verficar se há configuração de médias e vantagens',
    'Verificar os eventos configurados como médias e vantagens',
    'Verificar os eventos que compõe cada média e vantagem',
    'Verificar se os tipos, grupos estão corretos',
    'Caso não possua, realizar levantamento junto ao cliente',
    'CONFIGURAÇÃO DE PROVISÃO',
    'Conferir se já há configuração',
    'Verificar se existe uma data de início',
    'CADASTRO DE CONCURSO',
    'Verificar quantidade',
    'Verificar tipo',
    'Verificar número',
    'Verificar datas',
    'CADASTRO DE VINCULOS EMPREGATÍCIOS',
    'Verificar quantidade',
    'Verificar descrição',
    'Verificar se há controle de código',
    'Verificar tipo de regime trabalhista',
    'Verificar se há regime previdenciário',
    'Verificar categoria do trabalhador',
    'Verificar categoria sefip',
    'Verificar se é vínculo temporário',
    'Verificar motivo da rescisão',
    'Verificar se sai no caged',
    'Verificar se gera licença prêmio',
    'Verificar se Sai na Rais',
    'Verificar código da Rais',
    'Verificar se há campos adicionais',
    'CADASTRO DE PLANOS DE PREVIDÊNCIA E ASSISTÊNCIA',
    'Verificar a quantidade de planos',
    'Verificar os tipos de planos',
    'Verificar os regimes',
    'Verificar se é municipal, estadual ou federal',
    'Verificar se possui plano de segregação',
    'Verificar se é sujeito ao teto remuneratório',
    'Verificar vigências',
    'CADASTRO DE TIPOS DE ADMINISTRAÇÃO',
    'Verificar quantidade',
    'Verificar descrição',
    'Verificar natureza jurídica',
    'Verificar tipo de administração',
    'Verificar valor do subteto',
    'Verificar se há campos adicionais',
    'CADASTRO DE ENDEREÇOS (Definidos pelo usuário)',
    'Verificar se há estados, municípios, bairros e logradouros definidos pelo usuário',
    'Verificar quantidade de endereços que foram definidos pelo usuário',
    'Verificar os tipos dos logradouros',
    'Verificar descrição e município de cada logradouro',
    'Verificar CEP de cada logradouro',
    'Verificar nome e município dos bairros',
    'CADASTRO DE PESSOAS',
    'Conferir quantidade de pessoas',
    'Conferir se existe cadastro de pessoa jurídica (Empresa no cloud)',
    'Verificar se há pessoas com deficiências',
    'Conferir filiação',
    'Conferir principais dados pessoais (Nome, CPF, RG, Data de Nascimento, PIS, etc)',
    'Conferir dependentes',
    'Conferir se há dependentes de salário família, IRRF, pensão',
    'Conferir Nome, CPF e data de nascimento dos dependentes',
    'Conferir informações de contato',
    'Conferir informações de endereço',
    'Conferir contas bancárias',
    'Conferir número do registro de reservista (REVISAR)',
    'Verificar se há histórico de pessoas',
    'Conferir se campos adicionais',
    'Verificar nacionalidade e Naturalidade',
    'Verificar se há moléstia grave',
    'Verificar se há doenças e vacinas',
    'Verificar se há outros dados como raça, cor dos olhos, altura, peso, tipo sanguineo',
    'Verificar se há bases de outras empresas',
    'Verificar se há formações',
    'CADASTRO DE MATRÍCULAS',
    'Verificar quantidade',
    'Verificar os tipos de funcionários (funcionários, estagiários, autônomos, etc)',
    'Verificar o campo ocupa vaga',
    'Verificar se o código da matrícula está correto, bem como número do contrato (caso controle) e dígito verificador',
    'Verificar código eSocial',
    'Verificar data de admissão e data base',
    'Verificar se os históricos possuem ordem cronologica de data',
    'Verificar se a previdência informada está correta',
    'Verificar se há plano de previdencia em caso de RPPS',
    'Verificar qual a forma de pagamento',
    'Verificar se os dados bancários do último histórico está correto',
    'Verificar vínculo empregatício',
    'Verificar salário',
    'Verificar cargo',
    'Verificar nível salarial',
    'Verificar carga horária mensal e semanal',
    'Verificar configuração de férias',
    'Verificar unidade de pagamento',
    'Verificar funcionários efetivos em cargo comissionado (data de históricos)',
    'Verificar o campo tipo de provimento',
    'Verificar o campo hipótese legal e motivo de contratação em caso de temporários',
    'Verificar data de término e prorrogação de contrato em caso de temporários',
    'Verificar se há concurso/processo seletivo informado',
    'Verificar ocorrência sefip',
    'Verificar se é conselheiro tutelar',
    'Verificar organograma',
    'Verificar grupo funcional',
    'Verificar área de atuação',
    'Verificar lotação física',
    'Verificar se há campos adicionais',
    'CADASTRO DE EMPRESAS',
    'Verificar quantidade',
    'Verificar descrição',
    'Verificar nome fantasia',
    'Verificar CNPJ',
    'Verificar tipo de empresa (Geral, Sindicato, etc)',
    'Verificar natureza jurídica',
    'CADASTRO DE AGÊNCIAS BANCÁRIAS',
    'Verificar quantidade',
    'Verificar nome da agência',
    'Verificar número e dígito',
    'Verificar banco vinculado',
    'Verificar informações de endereço',
    'CADASTRO DE PROFISSIONAIS',
    'Verificar nome',
    'Verificar profissão',
    'Verificar número de conselho',
    'Verificar formação',
    'CADASTRO DE PERÍODOS AQUISITIVOS DE FÉRIAS',
    'Verificar se todos os funcionários possuem períodos',
    'Verificar os períodos de cada funcionário',
    'Verificar as concessões de férias',
    'Verificar se a data de pagamento das concessões estão corretas',
    'Verificar as datas de gozo de cada período',
    'Verificar os dias de falta, direito, cancelados, rescisão, suspensão e saldo',
    'Verificar situação dos períodos',
    'Configuração das Férias',
    'CADASTRO DE PERÍODOS AQUISITIVOS DE DÉCIMO TERCEIRO',
    'Verificar se todos os funcionários possuem períodos',
    'Verificar os períodos de cada funcionário',
    'Verificar as informações de pagamento',
    'Verificar os dias de direito, adquiridos, perdidos de cada ano',
    'Verificar situação de cada período',
    'CADASTRO DE GESTÃO DE PROCESSOS (Processos trabalhistas)',
    'Verificar se há processo administrativos no sistema',
    'Verificar informações do processo',
    'CADASTRO DE AFASTAMENTOS',
    'Verificar quantidade de afastamentos (por tipo ou funcionário)',
    'Verificar os tipos de afastamentos',
    'Verificar a quantidade de dias/horas',
    'Verificar as datas de afastamento (início, fim e retorno)',
    'CADASTRO DE OCORRÊNCIAS DISCIPLINARES',
    'Verificar quantidade',
    'Verificar tipo de ocorrência',
    'Verificar datas',
    'Verificar responsáveis',
    'Verificar motivos',
    'Verificar testemunhas',
    'CADASTRO DE AVISOS PRÉVIOS',
    'Verificar quantidade',
    'Verificar funcionários',
    'Verificar motivo de rescisão',
    'Verificar os tipos de aviso',
    'Verificar datas de início e fim',
    'Verificar quantidade de dias do aviso',
    'Verificar data prevista para o deligamento',
    'Verificar se há observações',
    'CADASTRO DE MOVIMENTAÇÕES DE PESSOAL',
    'Verificar quantidade de movimentações',
    'Verificar os tipos de movimentações de cada funcionário',
    'Verificar os atos de cada movimentação',
    'Verificar as datas de cada movimentação',
    'LANÇAMENTOS DE VARIÁVEIS',
    'Verificar quantidade',
    'Verificar quais funcionários possuem lançamentos',
    'Verificar competência inicial e final',
    'Verificar os eventos que foram lançados',
    'Verificar o valor de cada evento',
    'Verificar o tipo (vencimento ou desconto)',
    'Verificar se há observações',
    'CONSULTA DE CÁLCULO',
    'Verificar quais competências possuem cálculo',
    'Conferir valor total por competência',
    'Verificar se ha valores em processamentos como Férias, Rescisão, 13º, etc',
    'Verificar os eventos do cálculo',
    'Verificar os valores dos eventos',
    'HISTÓRICO DE REAJUSTE SALARIAL',
    'Verificar se há registro histórico de reajuste salarial',
    'Verificar valores anterior ao reajuste',
    'Verificar valores após o reajuste',
    'Verificar quais níveis sofreram o reajuste',
    'Verificar quais as datas dos reajustes ',
    'SERVIÇOS DE AUTÔNOMOS',
    'Verificar se há registro do serviço de autônomos',
    'Verificar quantidade',
    'Verificar as matriculas com lançamentos',
    'Verificar data dos lançamentos',
    'Verificar descrição',
    'Verificar número do documento',
    'Verificar CBO',
    'Verificar se deduz ISS ',
    'Verificar percentual da alíquota',
    'Verificar o valor de cada competência',
    'Verificar se há observações ou outros campos',
    'BASES DE OUTRAS EMPRESAS',
    'Verificar se há registro de bases de outras empresas',
    'Verificar quais os funcionários possuem o registro',
    'Verificar quais competências possuem o registro',
    'Verificar qual a empresa',
    'Verificar qual a categoria do trabalhador',
    'Verificar qual o valor da base de INSS',
    'Verificar qual o valor retido de INSS',
    'Verificar o valor de base de IRRF',
    'Verificar qual o valor retido de IRRF',
    'Verificar o processamento',
    'DIRF',
    'Verificar se há configuração de Dirf',
    'RAIS',
    'Verificar se há configuração de Rais',
    'INTEGRAÇÃO COM O TRANSPARÊNCIA',
    'Verificar se há configuração de agrupadores'
  ]),
  'Compras (Cloud)': parseTasksIntoSections([
    'PARÂMETROS GERAIS',
    'Por exercício',
    'Por entidade',
    'Geral',
    'SCRIPTS DE INTERAÇÃO',
    'Validar scripts',
    'PORTAIS DE DIVULGAÇÃO',
    'Portal da transparência (validar dados cadastrais, token e script)',
    'PNPC',
    'MODELO DE RELATÓRIOS',
    'Validar modelo de relatórios',
    'CASAS DECIMAIS',
    'Para a quantidade e Para o preço unitário',
    'PLATAFORMAS DE INFORMAÇÕES ELETRÔNICAS',
    'Validar se utiliza o compras.gov.br',
    'ESTRUTURA ORGANIZACIONAL',
    'Organogramas (sequencial: código e descrição)',
    'Entidades (Dados Gerais e de Contato)',
    'Órgãos externos (Descrição, CNPJ, Unidade e Esfera)',
    'CATÁLOGO',
    'Grupos e Classes (Descrição e Especificação)',
    'Unidades de medida (Definidos pelo Usuário e Padrões)',
    'Materiais e serviços (Código, Descrição, Grupo, Classe e Tipo)',
    'ORÇAMENTO',
    'Despesas (Descrição, Número, Organograma, Função, Subfunção, Programa, Ação, Natureza e Recurso)',
    'Objetos (Descrição)',
    'PESSOAS',
    'Veículos de Publicação (Fornecedor, CNPJ, Telefone, Tipo, Data de início e Situação)',
    'Fornecedores (Nome, Tipo, CPF/CNPJ, Data da inclusão e Situação)',
    'CRC (Fornecedor, Nº sequencial doc, Nº do CRC, Situação, Data de cadastro, Data da emissão, Data da validade, Cancelamento, Observações e Documentos)',
    'Responsáveis (Nome, CPF, Matrícula, Cargo, Natureza do cargo, Função, Complemento, Funcionário do Município?, Endereços, Emails, Telefones e Situação)',
    'Consórcios (Situação, Descrição, CNPJ, Consorciados e Dados Adicionais)',
    'Comissões de licitação (Tipo, Data da expiração, Data da exoneração, Tipo do ato, Número Oficia do ato, Data da designação e Finalidade)',
    'Grupos de assinantes',
    'BANCÁRIOS',
    'Agências (Banco, Nome da agência, Número, Dígito e Informações de endereço)',
    'ATOS',
    'Atos (Número, Tipo, Natureza do texto jurídico, Data da criação, Data da Publicação, Data a vigorar, Data da revogação, Ementa, Número o diário oficial, Fonte de divulgação e dados adicionais)',
    'Tipos de ato (Descrição e Classificação)',
    'Naturezas de texto jurídico',
    'Fontes de divulgação (Descrição, meio de comunicação e dados adicionais)',
    'INFORMAÇÕES DE ENTREGA',
    'Locais de entrega',
    'Prazos de entrega/execução (Descrição, TIpo, Unidade de entrega/execução, Nº de Dias)',
    'CADASTROS AUXILIARES',
    'Modalidades de licitação (Descrição, Modalidade legal, Sigla da modalidade e Limites Legais)',
    'Modelos de documentos (Descrição e Natureza)',
    'Formas de julgamento (Descrição, Tipo de licitação, Tipo de julgamento, Forma especial e Dados Adicionais)',
    'Tipos de objeto (Descrição, Tipo de objeto e Dados Adicionais)',
    'Tipos de interposição de recurso (Descrição e Classificação)',
    'Tipos de sessão de julgamento (Descrição e Classificação)',
    'Tipos de pareceres (Descrição e Classificação)',
    'Tipos de publicação do processo (Descrição e Classificação)',
    'Tipos de documento (Descrição, Tipo de certidão, Validade em dias e observações)',
    'Motivos de revogação/anulação/suspensão (Descrição, Tipo e Classificação)',
    'Endereços (Informações cadastrais de Logradouros, Condomínios, Bairros, Distritos, Estados e Municípios)',
    'Fundamentos Legais (Descrição e Situação)',
    'SOLICITAÇÕES DE COMPRA',
    'Organograma',
    'Data',
    'Nome do Solicitante',
    'Assunto',
    'Tipo de Necessidade',
    'Itens',
    'Valor unitário',
    'Valor total',
    'Status',
    'COTAÇÃO DE PREÇOS',
    'Cotações de preços (Data, Responsável, Forma de classificação, Condição de Pagamento, Prazo de entrega/execução, Validade, Objeto da Cotação e Observações)',
    'PROCESSOS',
    'Validar Informações Gerais',
    'Validar Itens do processo',
    'Validar dados adicionais',
    'Validar as fases: Processos, Em parecer contábil, Aguardando Autorização, Aguardando Formalização e Em parecer jurídico inicial.',
    'Sessão de Julgamento (Nº e ano do processo)',
    'Atos Finais (Nº e ano do processo)',
    'Pareceres (Nº e ano do processo)',
    'Textos do processo (Nº e ano do processo)',
    'REGISTROS DE PREÇOS',
    'Atas de registros de preços (Validar: Informações Gerais, Anexos e Dados Adicionais)',
    'Validar: Atas, Vigentes e Encerradas',
    'INTEGRAÇÕES ENTRE SISTEMAS',
    'Validar integração com o sistema contábil',
    'PRESTAÇÃO DE CONTAS',
    'Validar necessidade de campos relacionados às prestações de contas'
  ]),
  'Ponto (Cloud)': parseTasksIntoSections([
    'PARÂMETROS GERAIS',
    'Verificar se gera movimentação automaticamente na folha',
    'Verificar tipo de registro de ponto',
    'Verificar parâmetro de lançamento de ausências concomitantes',
    'PARÂMETROS DO PONTO',
    'Verificar tolerâncias de ponto',
    'Verificar prorrogação de período noturno',
    'Verificar período mínimo de intrajornada e interjornada',
    'Verificar demais parâmetros gerais de ponto',
    'Verificar motivos padrões de marcações de ponto',
    'RELÓGIOS',
    'Verificar quantidade de relógios cadastrados',
    'Verificar descrição dos relógios',
    'Verificar lotação física dos relógios',
    'Verificar tipos de relógios',
    'Verificar se os relógios são REP',
    'Verificar layout de importação dos relógios',
    'HORÁRIOS',
    'Verificar a quantidade de horários cadastrados',
    'Verificar a vigência dos horários',
    'Verificar hora inicial da alocação',
    'Verificar a tolerância de alocação',
    'Verificar as marcações esperadas do horário',
    'JORNADAS DE TRABALHO',
    'Verificar a quantidade dejornadas de trabalho',
    'Verificar o tipo de jornada',
    'Verificar a vigência da jornada',
    'Verificar os horários vinculados na jornada',
    'Verificar a classificação dos horários vinculados na jornada',
    'Verificar se é jornada de revezamento',
    'Verificar qual a escala de revezamento',
    'Verificar a data inicial do revezamento',
    'ESCALAS',
    'Verificar a quantidade de escalas',
    'Verificar a descrição da escala',
    'Verificar o tipo de escala',
    'Verificar as jornadas vinculadas na escala',
    'OCORRÊNCIAS',
    'Verificar a quantidade de ocorrências',
    'Verificar os históricos das ocorrências',
    'Verificar a descrição das ocorrências',
    'Verificar a classificação das ocorrências',
    'Verificar se a ocorrência deve gerar evento na folha',
    'Verificar se a fórmula da ocorrência foi importada',
    'FUNÇÕES DOS RELÓGIOS',
    'Verificar a quantidade de funções dos relógios',
    'Verificar a descrição das funções dos relógios',
    'Verificar o tipo das funções dos relógios',
    'PERÍODOS DE APURAÇÃO',
    'Verificar a quantidade de períodos de apuração',
    'Verificar as datas inicial e final dos períodos de apuração',
    'FERIADOS',
    'Verificar os feriados facultativos',
    'Verificar os feriados fixos',
    'TIPOS DE FUNÇÕES DOS RELÓGIOS',
    'Verificar a quantidade de tipos de funções dos relógios',
    'Verificar a descrição dos tipos de funções dos relógios',
    'Verificar a classificação dos tipos de funções',
    'MATRÍCULAS',
    'Verificar a quantidade de matrículas que registram ponto',
    'Verificar o número de cartão ponto',
    'Verificar o parâmetro de ponto',
    'Verificar se compensa horas',
    'Verificar a jornada de trabalho da matrícula',
    'LANÇAMENTO DE HORAS',
    'Verificar a quantidade de lançamentos de horas',
    'Verificar a data dos lançamentos',
    'Verificar a quantidade de horas lançadas',
    'PERMUTAS',
    'Verificar a quantidade de permutas',
    'Verificar o período das permutas',
    'Verificar a jornada das permutas',
    'COMPENSAÇÃO DE HORAS',
    'Verificar a quantidade de compensação de horas',
    'Verificar o tipo de compensação cadastrado',
    'Verificar a data de compensação cadastrada',
    'Verificar a quantidade de horas lançadas',
    'OCORRÊNCIAS DISCIPLINARES',
    'Verificar a quantidade de ocorrências disciplinares',
    'Verificar a data da ocorrência disciplinar',
    'Verificar o tipo de ocorrência disciplinar',
    'Verificar a quantidade lançada',
    'Verificar o período lançado',
    'Verificar o tipo de afastamento vinculado',
    'LANÇAMENTO DE AUSÊNCIAS',
    'Verificar a quantidade de lançamento de ausências',
    'Verificar o tipo de ausência cadastrado',
    'Verificar o período de ausência cadastrado',
    'Verificar a quantidade de horas lançadas',
    'Verificar o evento extraordinário vinculado',
    'Verificar se deve abonar ou não a ausência',
    'EVENTOS EXTRAORDINÁRIOS',
    'Verificar a quantidade de eventos extraordinários',
    'Verificar a descição do evento extraordinário',
    'Verificar o período do evento extraordinário',
    'Verificar se deve conceder folga',
    'Verificar a quantidade de dias de folga',
    'Verificar o período válido para as folgas',
    'Verificar as matrículas convocadas',
    'Verificar o período de convocação das matrículas',
    'Verificar os dias de abono das matrículas convocadas',
    'Verificar se há lançamentos de folgas para as matrículas',
    'GESTÃO DE MARCAÇÕES',
    'Verificar a quantidade de matrículas com marcações apuradas nos períodos de apuração',
    'Verificar as marcações apuradas',
    'Verificar as ocorrências apuradas'
  ]),
  'RH (Cloud)': parseTasksIntoSections([
    'CADASTRO DE PESSOAS',
    'Experiências Anteriores',
    'Manutenção de averbações',
    'Cursos',
    'Bolsa de estudos',
    'Formações',
    'CADASTRO DE CURSOS',
    'Verificar quantidade de cursos cadastrados',
    'Verificar tipos dos cursos',
    'Verificar modalidades dos cursos',
    'Verificar classificação dos cursos',
    'Verificar área de atuação dos cursos',
    'Verificar carga horária do curso',
    'Verificar Instituição',
    'Verificar período e duração',
    'Verificar objetivo',
    'CONFIGURAÇÃO DE PLANOS DE SAÚDE',
    'Verificar quantidade de planos',
    'Verificar informaões gerais',
    'Verificar informações de valores',
    'Verificar tabelas de valores',
    'Verificar faixas de subsídio',
    'CONFIGURAÇÃO DE VALE ALIMENTAÇÃO',
    'Verificar configuração de vale alimentação',
    'Verificar vigência',
    'Verificar tipo de vale',
    'Verificar valores e a unidade',
    'Verificar referência de cálculo',
    'Verificar tipo de desconto, se será descontado e valor de desconto, bem como data de início da cobertura',
    'Verificar operadora (empresa que fornece)',
    'Verificar os dias e tipos de afastamentos que serão descontados do calculo de vale',
    'CADASTRO DE NATUREZAS DE DIÁRIAS',
    'Verificar descrição',
    'Verificar vigência',
    'Verificar valor',
    'CADASTRO DE ROTAS',
    'Verificar quantidade de cadastros de rotas',
    'Verificar empresa de transporte',
    'Verificar meio de transporte',
    'Verificar perímetro',
    'Verificar valor e vigência',
    'CADASTRO DE DISTÂNCIAS',
    'Verificar quantidade de cadastros de distâncias',
    'Verificar referências de origem e referências de destino',
    'Verificar distância percorrida',
    'CONFIGURAÇÃO DE MARGEM CONSIGNAVEL',
    'Verificar quantidade de configurações',
    'Verificar percentual e qual a forma de aplicação do percentual',
    'Verificar eventos de composição, dedução e eventos de emprestimos',
    'CONFIGURAÇÃO DE ADICIONAIS',
    'Verificar quantidade de configurações',
    'Verificar classificação, se é anuenio, triênio, etc',
    'Verificar percentual e quando é feito o pagamento',
    'Verificar se utiliza experiências e contratos anteriores averbados',
    'Verificar faixa de progressão',
    'Verificar tipos de afastamentos que são considerados para suspensão dos períodos, bem como suspensão fixa',
    'Verificar se há afastamentos que cancelam os períodos e quantos dias para cancelar, se são dias contínuos e quando será cancelado',
    'Verificar tipos de movimentações',
    'CONFIGURAÇÃO DE LICENÇA PRÊMIO',
    'Verificar quantidade de configurações',
    'Verificar períodos de aquisição',
    'Verificar se é lançado afastamento ou não',
    'Verificar qual o tipo de afastamento',
    'Verificar faixa para aquisição da licença prêmio',
    'Verificar se há afastamentos que cancelam os períodos e quantos dias para cancelar, se são dias contínuos e quando será cancelado',
    'Verificar tipos de movimentações',
    'CADASTRO DE PROCEDIMENTOS MÉDICOS',
    'Verificar se há registro no sistema',
    'Verificar descrição do procedimento',
    'Verificar detalhamentos',
    'Verificar tipos dos procedimentos',
    'Verificar valores',
    'Verificar diagnósticos',
    'Verificar indicador biológico',
    'CADASTRO DE MODELOS DE PESQUISA DE SATISFAÇÃO',
    'Verificar se há registros',
    'Verificar os questionamentos e tipos de respostas',
    'PERÍODOS AQUISITIVOS DE LICENÇA PRÊMIO',
    'Verificar datas dos períodos de cada funcionário',
    'Verificar quantidades de dias do período, quantidade de dias de direito, suspensos, cancelados e de saldo',
    'Verificar situação dos períodos',
    'PERÍODOS AQUISITIVOS DE ADICIONAIS',
    'Verificar datas dos períodos de cada funcionário',
    'Verificar quantidades de dias do período, quantidade de dias suspensos e percentual de cada período',
    'Verificar situação dos períodos',
    'CADASTRO DE EMPRÉSTIMOS',
    'Verificar quantidade de empréstimos por funcionário',
    'Verificar data inicial e data final do emprestimo',
    'Verificar financiador (banco)',
    'Verificar número do contrato',
    'Verificar valor total',
    'Verificar número de parcelas',
    'Verificar resíduo',
    'Verificar verba',
    'Verificar data dos pagamentos e competências',
    'Verificar situação das parcelas',
    'CADASTRO DE MARGEM CONSIGNÁVEL',
    'Verificar funcionários com margens em todas as competências',
    'Verificar eventos de composição, dedução e eventos de emprestimos',
    'Verificar valores disponíveis',
    'DESPESAS DE PLANO DE SAÚDE',
    'Verificar funcionários com despesas nas competências',
    'Verificar situação',
    'Verificar custo do servidor, da entidade e valor total',
    'Verificar tipos das despesas e valores de cada tipo',
    'Verificar valores de titulares e dependentes',
    'DESPESAS DE VALE TRANSPORTE',
    'Verificar funcionários com despesas nas competências',
    'Verificar empresa de transporte',
    'Verificar rota',
    'Verificar dias a trabalhar',
    'Verificar passes no mês',
    'DESPESAS DE VALE ALIMENTAÇÃO',
    'Verificar funcionários com despesas nas competências',
    'Verificar custo do servidor, da entidade e valor total',
    'Verificar período de composição',
    'Verificar se há observações',
    'RECRUTAMENTO E SELEÇÃO',
    'Verificar se há registro de configurações de recrutamento',
    'Verificar informações gerais e classificações',
    'COMISSÕES DE AVALIAÇÕES',
    'Verificar quantidade de comissões',
    'Verificar data de vigência',
    'Verificar o tipo de comissão',
    'Verificar membros e suas funções',
    'AVALIAÇÕES',
    'Verificar quantidade de avaliações',
    'Verificar tipos de avaliações',
    'Verificar descrição',
    'Verificar conhecimento',
    'LOCAIS DE AVALIAÇÃO',
    'Verificar quantidade de locais',
    'Verificar empresa e informações referente ao local',
    'Verificar se há observações com outras informações',
    'VÍNCULO EMPREGATÍCIO',
    'Verificar configuração de adicional',
    'CONTRATOS TEMPORÁRIOS',
    'Verificar quantidade de funcionários temporários',
    'Verificar data de término e agendamento de rescisão',
    'Verificar situação',
    'SUBSTITUIÇÕES DE FUNCIONÁRIOS',
    'Verificar quantidade de funcionários substituídos',
    'Verificar funcionário titular e substituto',
    'Verificar cargo',
    'Verificar data inicial e data final',
    'APOSENTADORIAS E PENSÕES',
    'Verificar quantidade de processos de aposentadoria e pensão',
    'Verificar fases do processo',
    'Verificar tipo de processo',
    'Verificar entidade de origem',
    'Verificar solicitante',
    'Verificar contratos',
    'Verificar número do processo',
    'Verificar data e hora da entrada do processo',
    'Verificar tipo de cálculo e tipo de vencimento',
    'Verificar percentual quando os tipos de vencimentos forem proporcional',
    'Verificar competência e valores',
    'GESTÃO DE RECRUTAMENTO E SELEÇÃO',
    'Verificar quantidade de concursos e processos seletivos',
    'Verificar número de edital e descrição',
    'Verificar período de inscrição',
    'Verificar situação do concurso/processo seletivo',
    'Verificar regime jurídico',
    'Verificar cargos e suas informações (quantidade de vagas, valor inscrição, etc)',
    'Verificar tipo de avaliações',
    'Verificar se há campos adicionais',
    'Verificar editais vinculados',
    'Verificar inscrições e se foram deferidas ou indeferidas',
    'Verificar locais da prova, notas das avaliações e tipo de avaliação dos inscritos, data e se compareceu',
    'Verificar classificação de cada cargo',
    'Verificar convocação dos funcionários e suas fases',
    'Verificar recursos e se foram deferidos ou indeferidos',
    'EQUIPAMENTOS DE PROTEÇÃO',
    'Verificar quantidade de equipamentos',
    'Verificar os tipos de equipamentos',
    'Verificar descrição',
    'Verificar se há observações e campos adicionais',
    'JUNTAS MÉDICAS',
    'Verificar quantidade de juntas',
    'Verificar vigências',
    'Verificar profissionais e responsáveis',
    'RISCOS AMBIENTAIS',
    'Verificar quantidade de riscos',
    'Verificar descrições',
    'Verificar vigências',
    'Verificar responsáveis',
    'Verificar os riscos das lotações físicas',
    'Verificar o reconhecimento dos riscos',
    'Verificar medidas de controles',
    'Verificar cargos vinculados aos riscos',
    'Verificar atividades dos cargos',
    'Verificar riscos dos cargos',
    'Verificar insalubridade, periculosidade e tipo de aposentadoria dos cargos',
    'Verificar exames vinculados ao risco ambiental',
    'FORMULÁRIOS DE ANAMNESE',
    'Verificar quantidade de formulários',
    'Verificar campos do fórmulário',
    'CIPA',
    'Verificar quantidade de registros',
    'Verificar datas de eleição e vigências das CIPAS',
    'Verificar membros e suas funções',
    'AGENDAS',
    'Verificar quantidade de agendas de exames',
    'Verificar horários das agendas',
    'ATESTADOS',
    'Verificar quantidade de atestados',
    'Verificar unidade e quantidade (dias ou horas)',
    'Verificar data inicial e data final',
    'Verificar profissional responsável',
    'Verificar local de atendimento (sala)',
    'Verificar tipo de atestado',
    'Verificar motivo de consulta',
    'Verificar estabelecimento',
    'Verificar se o atestado gerou afastamento, qual o tipo de afastamento gerou e se foi deferido ou não',
    'Verificar se é decorrente de acompanhamento de dependentes e quais são os dependentes',
    'Verificar se há observações',
    'Verificar se há CIDs vinculados ao atestado',
    'Verificar se há anexos',
    'Verificar se há campos adicionais',
    'SOLICITAÇÃO DE EQUIPAMENTOS DE PROTEÇÃO',
    'Verificar quantidade',
    'Verificar descrição',
    'Verificar data de validade',
    'Verificar tipo de equipamento',
    'Verificar dados gerais',
    'Verificar quantidade e tamanhos',
    'CONTROLE DE ENTREGA DE EPIS',
    'Verificar quantidade',
    'Verificar EPI entregues',
    'Verificar EPI vencidos',
    'Verificar informações dos equipamentos',
    'REGISTRO DE EXTINTORES',
    'Verificar quantidade',
    'Verificar descrição',
    'Verificar informações dos extintores',
    'Verificar datas de instalação e validade',
    'Verificar situação',
    'ASO',
    'Verificar quantidade',
    'Verificar Resultado (Apto, Inapto, etc.)',
    'Verificar tipos dos exames',
    'Verificar datas de emissão e validade',
    'Verificar informações gerais',
    'Verificar avaliações clinicas',
    'Verificar formulários',
    'Verificar resultados',
    'LAUDOS MÉDICOS',
    'Verificar quantidade',
    'Verificar funcionários com laudos',
    'Verificar datas de avaliação',
    'Verificar junta e tipo de laudo',
    'Verificar situação dos laudos',
    'Verificar informações gerais dos laudos',
    'Verificar informações de atendimento médico',
    'Verificar Anamnese',
    'AGENDAMENTOS',
    'Verificar se existe agendamentos e sua quantidade',
    'Verificar informações das agendas',
    'ACIDENTES DE TRABALHO',
    'Verificar quantidade',
    'Verificar funcionários com acidentes',
    'Verificar data dos acidentes',
    'Verificar ocorrências e se existem CATs relacionados e suas informações',
    'Verificar informações do acidente (ocorrência, tipo de acidente, partes do corpo atingida, etc)',
    'Verificar os detalhes do acidente',
    'Verificar o formulário da anamnese',
    'Verificar informações do atendimento médico',
    'PPRA',
    'Verificar quantidade',
    'Verificar descrições',
    'Verificar data inicial e validade',
    'Verificar planejamento do PPRA',
    'Verificar informações gerais',
    'Verificar formulários',
    'Verificar se há anexos',
    'Verificar se há campos adicionais',
    'VISITAS TÉCNICAS',
    'Verificar quantidades',
    'Verificar lotações com registro de visitas',
    'Verificar a finalidade das visitas',
    'Verificar as datas das visitas',
    'Verificar os responsáveis pela visita',
    'Verificar as considerações',
    'AVALIAÇÕES DE DESEMPENHO',
    'Verificar quantidade de avaliações',
    'Verificar descrição e tipo',
    'Verificar duração',
    'Verificar quantidade de avaliações parciais',
    'Verificar informações gerais da avaliação',
    'Verificar avaliadores',
    'Verificar avaliação',
    'CONCEITOS',
    'Verificar quantidade',
    'Verificar descrições',
    'Verificar faixas e pontuações',
    'COMPETÊNCIAS',
    'Verificar quantidade de competências',
    'Verificar descrições',
    'Verificar detalhamentos',
    'Verificar conceitos',
    'GESTÃO DE AVALIAÇÕES DE DESEMPENHO',
    'Verificar quantidade',
    'Verificar funcionários com avaliação',
    'Verificar configuração da avaliação',
    'Verificar período',
    'Verificar nota final e situação',
    'Verificar informações das avaliações dos funcionários (formulários)',
    'SOLICITAÇÕES DE CURSOS',
    'Verificar quantidade',
    'Verificar cursos solicitados e quem solicitou',
    'Verificar datas e situações',
    'Verificar informações gerais da solicitação de curso'
  ])
};

// Normaliza o nome do produto removendo "(Cloud)" e caracteres especiais
const normalizeProductName = (name) => {
  if (!name) return '';
  return name
    .toLowerCase()
    .replace(/\(cloud\)/gi, '')
    .replace(/[()]/g, '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '') // Remove acentos
    .trim()
    .replace(/\s+/g, ' ');
};

// Função para buscar tarefas por nome de produto
// Retorna null se o produto não tiver processo de homologação
export const getDefaultTasksForProduct = (productName) => {
  if (!productName) return null;
  
  const normalizedInput = normalizeProductName(productName);
  
  // Busca APENAS match exato (considerando com e sem Cloud)
  for (const [key, tasks] of Object.entries(homologationTasksByProduct)) {
    const normalizedKey = normalizeProductName(key);
    if (normalizedKey === normalizedInput) {
      return tasks;
    }
  }
  
  // Se não encontrou match exato, retorna null (produto sem homologação)
  return null;
};

// Verifica se um produto tem processo de homologação
export const productHasHomologation = (productName) => {
  return getDefaultTasksForProduct(productName) !== null;
};