// Tarefas de migração por produto - extraídas do arquivo RotinasdeMigrao.txt
// IMPORTANTE: Produtos que não aparecem aqui NÃO têm processo de migração (ex: Conecta, Documentos)

const parseTasksIntoSections = (tasks) => {
  const sections = [];
  let currentSection = null;

  tasks.forEach(task => {
    // Se a tarefa está em UPPERCASE completo ou começa com "ETAPA" ou "MIGRAÇÃO", é uma seção
    if (task === task.toUpperCase() || task.startsWith('ETAPA') || task.startsWith('MIGRAÇÃO')) {
      if (currentSection) {
        sections.push(currentSection);
      }
      currentSection = { section: task, tasks: [] };
    } else if (currentSection) {
      currentSection.tasks.push(task);
    }
  });

  if (currentSection) {
    sections.push(currentSection);
  }

  return sections;
};

// Mapa de produtos com suas tarefas de migração
export const migrationTasksByProduct = {
  'e-Nota (Cloud)': parseTasksIntoSections([
    'DADOS CADASTRAIS',
    'Extrair Competências',
    'Extrair Indexadores',
    'Extrair Lista de Serviços',
    'Extair Incentivos Fiscais',
    'Extrair Serviços Pessoa',
    'Extrair Simples Nacional',
    'Extrair Incentivo Pessoa',
    'Extrair Contribuinte Prestador',
    'Extrair Isenção Pessoa',
    'Extrair Perfil Prestador',
    'Extrair Serviço Contribuinte Prestador',
    'Extrair Tributos Federais do Contribuinte Prestador',
    'Extrair e-mail Prestador',
    'Extrair Cadastro de Tomadores',
    'DADOS DE LANÇAMENTOS',
    'Extrair RPS',
    'Extrair Impressão de RPS',
    'Extrair Notas Fiscais (Prestador, Tomador, Serviço, Obra...)',
    'Extrair XML Notas Fiscais',
    'Extrair Substituição Nota / Estorno',
    'Extrair Cancelamento Nota',
    'Extrair Resumo Créditos Tributários',
    'Extrair Movimentação Créditos Tributários',
    'Extrair Denúncias',
    'Extrair Infrações',
    'Extrair Autos',
    'Extrair Guias de Pagamentos'
  ]),
  'Tributos (Cloud)': parseTasksIntoSections([
    'Dados Cadastrais',
    'Extrair Paises',
    'Extrair Estados',
    'Extrair Cidades',
    'Extrair Faces',
    'Extrair TiposLogradouros',
    'Extrair Distritos',
    'Extrair Bairros',
    'Extrair Ruas',
    'Extrair RuasBairros',
    'Extrair RuasCeps',
    'Extrair Loteamentos',
    'Extrair Condominios',
    'Extrair Bancos',
    'Extrair AgenciasBancarias',
    'Extrair TiposAtos',
    'Extrair FontesDivulgacao',
    'Extrair NaturezaTextoJuridico',
    'Extrair Atos',
    'Extrair AtosFontes',
    'Extrair Motivos',
    'Extrair Agrupamentos',
    'Extrair UnidadeMedida',
    'Extrair CamposAdicionais',
    'Extrair CamposAdicionaisCompl',
    'Extrair CamposAdicionaisReceitas',
    'Extrair CamposAdicionaisAgrupamentos',
    'Extrair Indexadores',
    'Extrair IndexadoresValores',
    'Extrair CreditosTributarios',
    'Extrair Receitas',
    'Extrair CreditosReceitas',
    'Extrair Feriados',
    'Extrair MateriaisServicos',
    'Extrair ConfigImovel',
    'Extrair ConfigInscrImobiliaria',
    'Extrair ConfigMelhoria',
    'Extrair ReceitasDiversasConfig',
    'Extrair NotasConfig',
    'Extrair ITBIConfig',
    'Extrair DividasConfig',
    'Extrair DividasConfigLivro',
    'Extrair PagamentosConfig',
    'Extrair ParcelamentosConfigCreditos',
    'Extrair ParcelamentosConfigTaxas',
    'Extrair Config2Via',
    'Extrair ParcelasConfig',
    'Extrair ParcelasConfigReceitas',
    'Extrair Pessoa',
    'Extrair PessoaTelefone',
    'Extrair PessoaEmail',
    'Extrair PessoaFisica',
    'Extrair PessoaJuridica',
    'Extrair PessoaFisicaDocumento',
    'Extrair PessoasEndereco',
    'Extrair PessoaSocio',
    'Extrair PessoaCampoAdicional',
    'Extrair PessoaCampoAdicionalCompl',
    'Extrair PessoaAverbacao',
    'Extrair PessoaContas',
    'Extrair PessoaSimples',
    'Extrair PessoaMEI',
    'Extrair Secoes',
    'Extrair SecaoCampoAdicional',
    'Extrair SecaoCampoAdicionalCompl',
    'Extrair PlantasValores',
    'Extrair Imobiliarias',
    'Extrair Imoveis',
    'Extrair ImoveisInfComplem',
    'Extrair ImoveisDebitoConta',
    'Extrair ImoveisCamposAdicionais',
    'Extrair ImoveisCamposAdicionaisCompl',
    'Extrair ImoveisEnglobados',
    'Extrair ImoveisTestadas',
    'Extrair ImoveisResponsaveis',
    'Extrair ImoveisMovimentacoes',
    'Extrair ImoveisHistoricos',
    'Extrair ImoveisMovimentacoes_historico',
    'Extrair ImoveisImagens',
    'Extrair Contador',
    'Extrair Cartorios',
    'Extrair ListaServicos',
    'Extrair Cnaes',
    'Extrair Atividades',
    'Extrair AtividadesCamposAdicionais',
    'Extrair AtividadesCamposAdicionaisCompl',
    'Extrair AtividadesRelacionamento',
    'Extrair Horarios',
    'Extrair HorariosDias',
    'Extrair TiposEntidades',
    'Extrair Economicos',
    'Extrair EconomicosCnaes',
    'Extrair EconomicosCnaesCamposAdicionais',
    'Extrair EconomicosCnaesCamposAdicionaisCompl',
    'Extrair EconomicosCnaesValores',
    'Extrair EconomicosServicos',
    'Extrair EconomicosServicosValores',
    'Extrair EconomicosCamposAdicionais',
    'Extrair EconomicosCamposAdicionaisCompl',
    'Extrair EconomicosMovimentacoes',
    'Extrair Melhorias',
    'Extrair MelhoriasMateriais',
    'Extrair MelhoriasBairros',
    'Extrair MelhoriasCamposAdicionais',
    'Extrair MelhoriasCamposAdicionaisCompl',
    'Extrair MelhoriasImoveis',
    'Extrair MelhoriasImoveisCamposAdicionais',
    'Extrair Engenheiros',
    'Extrair EngenheirosCBO',
    'Extrair Construtoras',
    'Extrair ConstrutorasEngenheiros',
    'Extrair Obras',
    'Extrair ObrasConstrutoras',
    'Extrair ObrasOpcoes',
    'Extrair ObrasOpcoesCompl',
    'Extrair ObrasEngenheiros',
    'Dados de Lançamentos',
    'Extrair ReceitasDiversas',
    'Extrair ReceitasDiversasMovimentacoes',
    'Extrair ReceitasDiversasCamposAdicionais',
    'Extrair ReceitasDiversasLancamentos',
    'Extrair ReceitasDiversasLancamentosReceitas',
    'Extrair Notas',
    'Extrair NotasServicos',
    'Extrair NotasMovtos',
    'Extrair ITBI',
    'Extrair ITBIImoveis',
    'Extrair ITBIImoveisProcessos',
    'Extrair ITBIImoveisItens',
    'Extrair ITBICompradores',
    'Extrair  ImoveisMovimentacoes',
    'Extrair Desmembramentos',
    'Extrair DesmembramentosImoveis',
    'Extrair DesmembramentosOrigem',
    'Extrair Remembramentos',
    'Extrair RemembramentosImoveis',
    'Extrair CorrecaoDividas',
    'Extrair Dividas',
    'Extrair DividasReceitas',
    'Extrair DividasComentario',
    'Extrair DividasResponsaveis',
    'Extrair DividasStatus',
    'Extrair DividasDoctos',
    'Extrair DividasDebitos',
    'Extrair lancamentos',
    'Extrair Guias',
    'Extrair NumerosBaixas',
    'Extrair GuiasEmitidas',
    'Extrair GuiasEmitidasReceitas',
    'Extrair GuiaUnificada',
    'Extrair GuiaUnificadaComposicoes',
    'Extrair PagamentosConvenios',
    'Extrair Pagamentos',
    'Extrair PagamentosDetalhamentos',
    'Extrair PagamentosTaxas',
    'Extrair Parcelamentos',
    'Extrair ParcelamentosCancelados',
    'Extrair ParcelamentosCreditos',
    'Extrair ParcelamentosReferentes',
    'Extrair ParcelamentosOrigem',
    'Extrair ParcelamentosComposicoes',
    'Extrair ParcelamentosAbatimentos',
    'Extrair ParcelamentosOrdens',
    'Extrair ParcelamentosParcelas',
    'Extrair ParcelamentosTaxas',
    'Extrair Convenios',
    'Extrair ConveniosCreditos',
    'Extrair ConveniosMensagens',
    'Extrair Beneficios',
    'Extrair Tabelas',
    'Extrair TabelasCampos',
    'Extrair TabelasConjuntos',
    'Extrair TabelasRelacionadas',
    'Extrair TabelasValores',
    'Extrair Competencias',
    'Extrair Parcelas',
    'Extrair ParcelasParcelas',
    'Extrair ParcelasReceitas',
    'Extrair Lancamentos',
    'Extrair LancamentosEnglobados',
    'Extrair LancamentosReceitas',
    'Extrair LancamentosDebitos',
    'Extrair LancamentosDebitosReceitas',
    'Extrair LancamentosDeclaracoes',
    'Extrair LancamentosDeclaracoesServicos',
    'Extrair ManutencoesCalculo',
    'Extrair ManutencoesCalculoCreditos',
    'Extrair ManutencoesCalculoReferentes',
    'Extrair ManutencoesCalculoReceitas',
    'Extrair ManutencoesCalculoGuias',
    'Extrair ManutencoesCalculoMovto'
  ]),
  'Procuradoria (Cloud)': parseTasksIntoSections([
    'Dados Cadastrais',
    'Extrair Tipos Custas Processuais',
    'Extrair Advogados',
    'Extrair Tribunais',
    'Extrair Comarcas',
    'Extrair Varas',
    'Extrair Praças',
    'Extrair Áreas',
    'Extrair Assuntos',
    'Extrair Classes Pai',
    'Extrair Classes Filhas',
    'Extrair Naturezas Jurídicas',
    'Extrair Naturezas Textos',
    'Extrair Motivos',
    'Extrair Tipos Documentos',
    'Dados de Lançamentos',
    'Extrair dados de Execuções',
    'Extrair dados de config execuções fiscais',
    'Extrair dados de execuções fiscais',
    'Extrair dados de execuções fiscais mov',
    'Extrair dados de execuções fiscais dividas',
    'Extrair dados de execuções fiscais custas',
    'Extrair dados de protestos',
    'Extrair dados de protestos movtos',
    'Extrair dados de apensos',
    'Extrair dados de protestos',
    'Extrair dados de Documentos'
  ]),
  'Livro Eletrônico': parseTasksIntoSections([
    'Dados Cadastrais',
    'Extrair Competências',
    'Extrair Indexadores',
    'Extrair Lista de Serviços',
    'Extrair CNAE',
    'Extrair Contadores',
    'Extrair Contribuintes',
    'Extrair Contribuintes Serviços / Movimento',
    'Extrair Movimento Optante Simples',
    'Extarir Incentivos Fiscais',
    'Extrair Contribuinte Incentivos Fiscais',
    'Extrair Entidades Especiais',
    'Extrair Plano de Conta',
    'Extrair Simples Nacional',
    'Extrair Cadastro de Tomadores',
    'Extrair Cadastro de Prestadores',
    'Dados de Lançamentos',
    'Extrair Notas Fiscais',
    'Extrair Declarações',
    'Extrair Notas Avulsas'
  ]),
  'Protocolo (Cloud)': parseTasksIntoSections([
    'Dados Cadastrais',
    'Extrair Pessoa',
    'Extrair Pessoa e-Mail',
    'Extrair Pessoa Telefone',
    'Extrair Paises',
    'Extrair Estados',
    'Extrair Cidades',
    'Extrair Bairros',
    'Extrair Tipo Logradouro',
    'Extrair Logradouro',
    'Extrair Bairro Logradouro',
    'Extrair CEP Logradouro',
    'Extrair Loteamento',
    'Extrair Organograma Config',
    'Extrair Organograma Nível',
    'Extrair Organograma',
    'Extrair Organograma Responsável',
    'Extrair Feriado',
    'Extrair Indexadores',
    'Extrair Documentos',
    'Extrair Classificação',
    'Extrair Assuntos',
    'Extrair Assuntos Documentos',
    'Extrair Assuntos Organogramas',
    'Extrair Taxas',
    'Extrair Taxas Valores',
    'Extrair Assuntos Taxas',
    'Dados de Lançamentos',
    'Extrair Protocolos',
    'Extrair Processos',
    'Extrair Processos Partes',
    'Extrair Entrega Documentos',
    'Extrair Andamentos',
    'Extrair Pareceres',
    'Extrair Arquivamentos',
    'Extrair Localização'
  ]),
  'Contabil': parseTasksIntoSections([
    'Dados Cadastrais',
    'Extrair Credores',
    'Extrair Responsáveis',
    'Extrair Ordenadores',
    'Extrair Equipe Planejamento',
    'Extrair Localizadores',
    'Extrair Produtos',
    'Extrair Unidade de Medida',
    'Extrair Comprovantes',
    'Extrair Dividas',
    'Extrair Precatórios',
    'Extrair Diarias',
    'Extrair Bancos',
    'Extrair Agências',
    'Extrair Contas Bancárias',
    'Extrair Contas Contábeis',
    'Extrair Retenções',
    'Extrair Cheques',
    'Extrair Retenções Ativar',
    'Extrair Configuração Componentes',
    'Extrair Configuração Contas Correntes',
    'Dados de Lançamentos',
    'Extrair Receitas Não Previstas',
    'Extrair Receitas Extras',
    'Extrair Receitas Extras Ativar',
    'Extrair Alterações Receitas',
    'Extrair Programação Receitas',
    'Extrair Despesas Não Previstas',
    'Extrair Alteração Orçamentária Despesa - Suplementações',
    'Extrair Alteração Orçamentária Despesa - Sanção',
    'Extrair Programação Despesas',
    'Extrair Bloqueios',
    'Extrair Desbloqueios',
    'Extrair Lançamento Receitas',
    'Extrair Anulação Lançamento Receitas',
    'Extrair Arrecadações',
    'Extrair Anulação Arrecadações',
    'Extrair Arrecadações Extras',
    'Extrair Anulação Arrecadações Extras',
    'Extrair Devoluções Receitas',
    'Extrair Empenhos',
    'Extrair SubEmpenhos',
    'Extrair Em liquidações',
    'Extrair Liquidações',
    'Extrair Pagamentos',
    'Extrair Despesas Extras',
    'Extrair Prestação de Contas',
    'Extrair Anulação Pagamentos',
    'Extrair Anulação Liquidações',
    'Extrair Anulação Em Liquidações',
    'Extrair Anulação SubEmpenhos',
    'Extrair Anulação Empenhos',
    'Extrair Anulação Despesas Extras',
    'Extrair Adiantamentos',
    'Extrair Despesas Ordena',
    'Extrair Bloqueios',
    'Extrair Desbloqueios',
    'Extrair Empenhos',
    'Extrair SubEmpenhos',
    'Extrair Em Liquidações',
    'Extrair Liquidações',
    'Extrair Pagamentos',
    'Extrair Anulação Pagamentos',
    'Extrair Anulação Liquidações',
    'Extrair Anulação Em Liquidações',
    'Extrair Anulação SubEmpenhos',
    'Extrair Anulação Empenhos',
    'Extrair Cvs Restos',
    'Extrair Lançamentos Contábeis',
    'Extrair Lançamentos Contábeis Contas Correntes',
    'Extrair Saldos Iniciais',
    'Extrair Saldos Iniciais Contas Correntes',
    'Extrair Saldos Abertura',
    'Extrair Saldos Abertura Contas Correntes',
    'Extrair Escrituração',
    'Extrair Consignações',
    'Extrair Contas Bancárias Aplicações',
    'Extrair Contas Bancárias',
    'Extrair Contas Bancárias Transferências',
    'Extrair Contas Bancárias Transferências Aplicações',
    'Extrair Créditos Tributários Curto Prazo',
    'Extrair Créditos Tributários Longo Prazo',
    'Extrair Depósitos',
    'Extrair Dívida Ativa Não Tributária Curto Prazo',
    'Extrair Dívida Ativa Não Tributária Longo Prazo',
    'Extrair Dívida Ativa Tributária Curto Prazo',
    'Extrair Dívida Ativa Tributária Longo Prazo',
    'Extrair Faturas e Duplicatas Curto Prazo',
    'Extrair Faturas e Duplicatas Longo Prazo',
    'Extrair Imobilizado',
    'Extrair Pagamentos Antecipados',
    'Extrair Transferências Concedidas',
    'Extrair Transferências Recebidas',
    'Extrair VPA',
    'Extrair VPD'
  ]),
  'Contábil (Cloud)': parseTasksIntoSections([
    'Dados Cadastrais',
    'Extrair Credores',
    'Extrair Responsáveis',
    'Extrair Ordenadores',
    'Extrair Equipe Planejamento',
    'Extrair Localizadores',
    'Extrair Produtos',
    'Extrair Unidade de Medida',
    'Extrair Comprovantes',
    'Extrair Dividas',
    'Extrair Precatórios',
    'Extrair Diarias',
    'Extrair Bancos',
    'Extrair Agências',
    'Extrair Contas Bancárias',
    'Extrair Contas Contábeis',
    'Extrair Retenções',
    'Extrair Cheques',
    'Extrair Retenções Ativar',
    'Extrair Configuração Componentes',
    'Extrair Configuração Contas Correntes',
    'Dados de Lançamentos',
    'Extrair Receitas Não Previstas',
    'Extrair Receitas Extras',
    'Extrair Receitas Extras Ativar',
    'Extrair Alterações Receitas',
    'Extrair Programação Receitas',
    'Extrair Despesas Não Previstas',
    'Extrair Alteração Orçamentária Despesa - Suplementações',
    'Extrair Alteração Orçamentária Despesa - Sanção',
    'Extrair Programação Despesas',
    'Extrair Bloqueios',
    'Extrair Desbloqueios',
    'Extrair Lançamento Receitas',
    'Extrair Anulação Lançamento Receitas',
    'Extrair Arrecadações',
    'Extrair Anulação Arrecadações',
    'Extrair Arrecadações Extras',
    'Extrair Anulação Arrecadações Extras',
    'Extrair Devoluções Receitas',
    'Extrair Empenhos',
    'Extrair SubEmpenhos',
    'Extrair Em liquidações',
    'Extrair Liquidações',
    'Extrair Pagamentos',
    'Extrair Despesas Extras',
    'Extrair Prestação de Contas',
    'Extrair Anulação Pagamentos',
    'Extrair Anulação Liquidações',
    'Extrair Anulação Em Liquidações',
    'Extrair Anulação SubEmpenhos',
    'Extrair Anulação Empenhos',
    'Extrair Anulação Despesas Extras',
    'Extrair Adiantamentos',
    'Extrair Despesas Ordena',
    'Extrair Bloqueios',
    'Extrair Desbloqueios',
    'Extrair Empenhos',
    'Extrair SubEmpenhos',
    'Extrair Em Liquidações',
    'Extrair Liquidações',
    'Extrair Pagamentos',
    'Extrair Anulação Pagamentos',
    'Extrair Anulação Liquidações',
    'Extrair Anulação Em Liquidações',
    'Extrair Anulação SubEmpenhos',
    'Extrair Anulação Empenhos',
    'Extrair Cvs Restos',
    'Extrair Lançamentos Contábeis',
    'Extrair Lançamentos Contábeis Contas Correntes',
    'Extrair Saldos Iniciais',
    'Extrair Saldos Iniciais Contas Correntes',
    'Extrair Saldos Abertura',
    'Extrair Saldos Abertura Contas Correntes',
    'Extrair Escrituração',
    'Extrair Consignações',
    'Extrair Contas Bancárias Aplicações',
    'Extrair Contas Bancárias',
    'Extrair Contas Bancárias Transferências',
    'Extrair Contas Bancárias Transferências Aplicações',
    'Extrair Créditos Tributários Curto Prazo',
    'Extrair Créditos Tributários Longo Prazo',
    'Extrair Depósitos',
    'Extrair Dívida Ativa Não Tributária Curto Prazo',
    'Extrair Dívida Ativa Não Tributária Longo Prazo',
    'Extrair Dívida Ativa Tributária Curto Prazo',
    'Extrair Dívida Ativa Tributária Longo Prazo',
    'Extrair Faturas e Duplicatas Curto Prazo',
    'Extrair Faturas e Duplicatas Longo Prazo',
    'Extrair Imobilizado',
    'Extrair Pagamentos Antecipados',
    'Extrair Transferências Concedidas',
    'Extrair Transferências Recebidas',
    'Extrair VPA',
    'Extrair VPD'
  ]),
  'Planejamento': parseTasksIntoSections([
    'Dados Cadastrais',
    'Extrair Configurações - PPAs',
    'Extrair Configurações - LDOs',
    'Extrair Configurações - LOAs',
    'Extrair Configurações - Funcionais',
    'Extrair Configurações - Natureza Despesa',
    'Extrair Configurações - Natureza Receita',
    'Extrair Configurações - Organogramas',
    'Extrair Configurações - Plano de Contas',
    'Extrair Configurações - Recursos',
    'Extrair Configurações - Parâmetros Orçamentários',
    'Extrair Configurações - Parâmetros Escrituração',
    'Extrair Tipos Administração',
    'Extrair Tipos Compensações',
    'Extrair Tipos Renuncias',
    'Extrair Tipos Resultados Nominais',
    'Extrair Tipos Riscos fiscais',
    'Extrair Tipos Responsaveis',
    'Extrair Tipos Alteração Orçamentária Receita',
    'Extrair Tipos Bloqueios',
    'Extrair Transações Financeiras',
    'Extrair Tipos Comprovantes',
    'Extrair Tipos Precatórios',
    'Extrair Tipos Dividas',
    'Extrair Tipos Movimentos',
    'Extrair Tipos documentos',
    'Extrair Tipos Atos',
    'Extrair Tipos Logradouros',
    'Extrair Tipos Aplicações',
    'Extrair Alteracao Despesa',
    'Extrair Fontes de Divulgação',
    'Extrair Tipos Alteração Orçamentária Receita Ativar',
    'Extrair Tipos Bloqueios Ativar',
    'Extrair Transações Financeiras Ativar',
    'Extrair Tipos Movimentos Ativar',
    'Extrair Tipos Documentos Ativar',
    'Extrair Tipos Aplicações Ativar',
    'Extrair Alteração Despesa Ativar',
    'Extrair Data Inicial',
    'Extrair Data Abertura',
    'Extrair Fase Saldos',
    'Extrair Países',
    'Extrair - Estados',
    'Extrair Cidades',
    'Extrair Logradouros',
    'Extrair Distritos',
    'Extrair Bairros',
    'Extrair Loteamentos',
    'Extrair Condominios',
    'Extrair Natureza Texto Jurídico',
    'Extrair Recursos',
    'Extrair Funções',
    'Extrair SubFunções',
    'Extrair Programas',
    'Extrair Ações',
    'Extrair Dedução Receitas',
    'Extrair Organogramas',
    'Extrair Natureza Despesa',
    'Extrair Natureza Receita',
    'Extrair Dedução Receitas Ativar',
    'Extrair Atos',
    'Dados de Lançamentos',
    'Extrair Receitas PPA',
    'Extrair Grupo Despesas PPA',
    'Extrair Despesas PPA',
    'Extrair Metas Fiscais Despesas PPA',
    'Extrair Orientações Estratégicas',
    'Extrair Audiências',
    'Extrair Sugestões',
    'Extrair Receitas LDO',
    'Extrair Grupo Despesas LDO',
    'Extrair Despesas LDO',
    'Extrair Renúncias Fiscais',
    'Extrair Expansões Despesa',
    'Extrair Resultado Nominal',
    'Extrair Riscos Fiscais',
    'Extrair Projeções Atuariais',
    'Extrair Atuário',
    'Extrair Metas Fiscais Despesas LDO',
    'Extrair Metas Fiscais Receitas LDO',
    'Extrair Transferências Financeiras LDO',
    'Extrair Receitas LOA',
    'Extrair Grupo Despesas LOA',
    'Extrair Despesas LOA',
    'Extrair Transferências Financeiras LOA'
  ]),
  'Planejamento (Cloud)': parseTasksIntoSections([
    'Dados Cadastrais',
    'Extrair Configurações - PPAs',
    'Extrair Configurações - LDOs',
    'Extrair Configurações - LOAs',
    'Extrair Configurações - Funcionais',
    'Extrair Configurações - Natureza Despesa',
    'Extrair Configurações - Natureza Receita',
    'Extrair Configurações - Organogramas',
    'Extrair Configurações - Plano de Contas',
    'Extrair Configurações - Recursos',
    'Extrair Configurações - Parâmetros Orçamentários',
    'Extrair Configurações - Parâmetros Escrituração',
    'Extrair Tipos Administração',
    'Extrair Tipos Compensações',
    'Extrair Tipos Renuncias',
    'Extrair Tipos Resultados Nominais',
    'Extrair Tipos Riscos fiscais',
    'Extrair Tipos Responsaveis',
    'Extrair Tipos Alteração Orçamentária Receita',
    'Extrair Tipos Bloqueios',
    'Extrair Transações Financeiras',
    'Extrair Tipos Comprovantes',
    'Extrair Tipos Precatórios',
    'Extrair Tipos Dividas',
    'Extrair Tipos Movimentos',
    'Extrair Tipos documentos',
    'Extrair Tipos Atos',
    'Extrair Tipos Logradouros',
    'Extrair Tipos Aplicações',
    'Extrair Alteracao Despesa',
    'Extrair Fontes de Divulgação',
    'Extrair Tipos Alteração Orçamentária Receita Ativar',
    'Extrair Tipos Bloqueios Ativar',
    'Extrair Transações Financeiras Ativar',
    'Extrair Tipos Movimentos Ativar',
    'Extrair Tipos Documentos Ativar',
    'Extrair Tipos Aplicações Ativar',
    'Extrair Alteração Despesa Ativar',
    'Extrair Data Inicial',
    'Extrair Data Abertura',
    'Extrair Fase Saldos',
    'Extrair Países',
    'Extrair - Estados',
    'Extrair Cidades',
    'Extrair Logradouros',
    'Extrair Distritos',
    'Extrair Bairros',
    'Extrair Loteamentos',
    'Extrair Condominios',
    'Extrair Natureza Texto Jurídico',
    'Extrair Recursos',
    'Extrair Funções',
    'Extrair SubFunções',
    'Extrair Programas',
    'Extrair Ações',
    'Extrair Dedução Receitas',
    'Extrair Organogramas',
    'Extrair Natureza Despesa',
    'Extrair Natureza Receita',
    'Extrair Dedução Receitas Ativar',
    'Extrair Atos',
    'Dados de Lançamentos',
    'Extrair Receitas PPA',
    'Extrair Grupo Despesas PPA',
    'Extrair Despesas PPA',
    'Extrair Metas Fiscais Despesas PPA',
    'Extrair Orientações Estratégicas',
    'Extrair Audiências',
    'Extrair Sugestões',
    'Extrair Receitas LDO',
    'Extrair Grupo Despesas LDO',
    'Extrair Despesas LDO',
    'Extrair Renúncias Fiscais',
    'Extrair Expansões Despesa',
    'Extrair Resultado Nominal',
    'Extrair Riscos Fiscais',
    'Extrair Projeções Atuariais',
    'Extrair Atuário',
    'Extrair Metas Fiscais Despesas LDO',
    'Extrair Metas Fiscais Receitas LDO',
    'Extrair Transferências Financeiras LDO',
    'Extrair Receitas LOA',
    'Extrair Grupo Despesas LOA',
    'Extrair Despesas LOA',
    'Extrair Transferências Financeiras LOA'
  ]),
  'Tesouraria': parseTasksIntoSections([
    'Dados de Lançamentos',
    'Extrair Ajustes Bancários',
    'Extrair Transferências',
    'Extrair Conciliações Bancárias',
    'Extrair Saldos Bancários',
    'Extrair Gestão Bancária'
  ]),
  'Tesouraria (Cloud)': parseTasksIntoSections([
    'Dados de Lançamentos',
    'Extrair Ajustes Bancários',
    'Extrair Transferências',
    'Extrair Conciliações Bancárias',
    'Extrair Saldos Bancários',
    'Extrair Gestão Bancária'
  ]),
  'Folha (Cloud)': [
    {
      section: 'Dados Cadastrais',
      tasks: [
        'Extrair Configurações de Entidades',
        'Extrair Configuração de Campos Adicionais',
        'Extrair Países',
        'Extrair Estados',
        'Extrair Municípios',
        'Extrair Bairros',
        'Extrair Logradouros',
        'Extrair Bancos',
        'Extrair Agências Bancárias',
        'Extrair Feriados',
        'Extrair Formações',
        'Extrair Formação das Pessoas',
        'Extrair Fonte de Divulgação',
        'Extrair Natureza de Texto Jurídico',
        'Extrair Motivos de Alteração Salarial',
        'Extrair Motivos de Alteração de Cargo',
        'Extrair Tipos de Movimentação de Pessoal',
        'Extrair Tabelas Auxiliares',
        'Extrair Funções',
        'Extrair Planos de Cargos e Salários',
        'Extrair Planos Faixas e Níveis Salariais',
        'Extrair Classes e Referências dos Níveis Salariais',
        'Extrair Categoria do Trabalhador',
        'Extrair Configuração de Adicional',
        'Extrair Motivos Rescisão',
        'Extrair Tipos Afastamentos',
        'Extrair Vinculos Empregatícios',
        'Extrair Sincronização de CBO´s',
        'Extrair Eventos',
        'Extrair Entidades e Entidades Folha',
        'Extrair Grupos Funcionais',
        'Extrair Sincronização das Contas',
        'Extrair Pessoas Jurídicas',
        'Extrair Pessoas Físicas',
        'Extrair Dependentes',
        'Extrair Tipos de Função de Relógio',
        'Extrair Horários',
        'Extrair Jornada de Trabalho',
        'Extrair Tipos Cargos',
        'Extrair Niveis',
        'Extrair Cargos',
        'Extrair Config Organ',
        'Extrair Niveis Organ',
        'Extrair Entidades Organ',
        'Extrair Organogramas',
        'Extrair Configuração de Lotações Físicas',
        'Extrair Lotações Físicas',
        'Extrair Configuração de Encargos',
        'Extrair Tipos de Bases',
        'Extrair Configuração de Médias e Vantagens',
        'Extrair Configuração de Licença Prêmio',
        'Extrair Licpremio Config',
        'Extrair Licpremio Faixas',
        'Extrair Tipos Atos',
        'Extrair Tipos Movpes',
        'Extrair Planos de Previdência',
        'Extrair Configuração de Cancelamento de Férias',
        'Extrair Configuração de Férias',
        'Extrair Concursos',
        'Extrair Funcionários',
        'Extrair Conselheiros Tutelares',
        'Extrair Estagiários',
        'Extrair Autônomos',
        'Extrair Profissionais',
        'Extrair Aposentados',
        'Extrair Pensionistas',
        'Extrair Serviços de Autônomos',
        'Extrair Tipos de Atestados',
        'Extrair Motivos Consultas Médicas',
        'Extrair Motivos Faltas',
        'Extrair Configuração da DIRF',
        'Extrair Locais Trab',
        'Extrair Hist Funcionários',
        'Extrair Hist Salariais',
        'Extrair Hist Cargos',
        'Extrair Dependentes Func'
      ]
    },
    {
      section: 'Dados de Lançamentos',
      tasks: [
        'Extrair Período Aquisitivo de Férias',
        'Extrair Período Aquisitivo de Décimo Terceiro',
        'Extrair Cálculo de Folha de Rescisão',
        'Extrair Cálculo de Folha Mensal',
        'Extrair Cálculo de Folha de Décimo Terceiro',
        'Extrair Cálculo de Folha de Férias',
        'Extrair Concessão de Férias',
        'Extrair Concessão de Décimo Terceiro',
        'Extrair Movimentações de Folhas',
        'Extrair Controle de Envio do eSocial',
        'Extrair Acid Trab',
        'Extrair Funcoes Exerc',
        'Extrair Funcoes Func',
        'Extrair Atos e Fontes Atos',
        'Extrair Atos Func',
        'Extrair Afastamentos',
        'Extrair Rescisões',
        'Extrair Cessação Aposentados',
        'Extrair Cessação e Suspensão Pensionistas',
        'Extrair Licenca Premio e Licenca Premio Disp',
        'Extrair Beneficiarios',
        'Extrair Atestados',
        'Extrair Transferências',
        'Extrair Movimentação de Pessoal',
        'Extrair Lançamentos de Eventos',
        'Extrair Faltas',
        'Extrair Linhas Onibus',
        'Extrair Faixas ValTransp',
        'Extrair Vales Transportes',
        'Extrair Caracteristicas',
        'Extrair Funcionarios Prop Adic',
        'Extrair Empresas Ant',
        'Extrair Ferias Proc',
        'Extrair Bases Calc',
        'Extrair Modalidades GFIP',
        'Extrair Variáveis'
      ]
    }
  ],
  'Compras (Cloud)': [
    {
      section: 'Dados Cadastrais',
      tasks: [
        'Extrair Configurações - Configurações Organogramas',
        'Extrair Configurações - Organograma Orgão',
        'Extrair Configurações - Organograma Unidade',
        'Extrair Configurações - Organograma Centro Custo',
        'Extrair Configurações - Parâmetro Exercício',
        'Extrair Configurações - Parâmetro Exercício Compras',
        'Extrair Países',
        'Extrair Estados',
        'Extrair Municípios',
        'Extrair Grupos',
        'Extrair Classes',
        'Extrair Unidades de Medida',
        'Extrair Materiais e Serviços',
        'Extrair Formas Julgamento',
        'Extrair Regime Execução',
        'Extrair Orgão Externo',
        'Extrair Tipo Objeto',
        'Extrair Prazo Entrega',
        'Extrair Tipo Interposição Recurso',
        'Extrair Tipo Publicação Processo',
        'Extrair Modalidade',
        'Extrair Condição Pagamento',
        'Extrair Local Entrega',
        'Extrair Tipo Documento',
        'Extrair Cargo Responsável',
        'Extrair Despesa',
        'Extrair Tipo Anulação Revogação',
        'Extrair Tipo Sessão Julgamento',
        'Extrair Natureza Jurídica',
        'Extrair Fundamentação Legal',
        'Extrair Tipo Ato',
        'Extrair Fonte Divulgação',
        'Extrair Natureza Texto Jurídico',
        'Extrair Responsável',
        'Extrair Ato',
        'Extrair Agência',
        'Extrair Comissão Licitação',
        'Extrair Fornencedor',
        'Extrair Fornecedor Sócio',
        'Extrair Fornecedor Documento',
        'Extrair Fornecedor Documento Item',
        'Extrair Consórcio',
        'Extrair Veículo Publicação'
      ]
    },
    {
      section: 'Dados de Lançamentos',
      tasks: [
        'Extrair Solicitação Compra',
        'Extrair Solicitação Compra Item',
        'Extrair Solicitação Compra Despesa',
        'Extrair Solicitação Compra Atualizar Valores',
        'Extrair Cotação Preço',
        'Extrair Cotação Preço Itens',
        'Extrair Cotação Vínculo Solicitação',
        'Extrair Cotação Participantes',
        'Extrair Cotação Participantes Item',
        'Extrair Cotação Finalizar',
        'Extrair Processo Adm',
        'Extrair Processo Adm Documento',
        'Extrair Processo Adm Entidade',
        'Extrair Processo Adm Tipos Textos',
        'Extrair Processo Adm Textos',
        'Extrair Processo Adm Anexos',
        'Extrair Processo Adm Pareceres',
        'Extrair Processo Adm Item Livre',
        'Extrair Processo Adm Item Reservado',
        'Extrair Processo Adm Despesa',
        'Extrair Processo Adm Lote',
        'Extrair Processo Adm Lote Item',
        'Extrair Processo Adm Entidade Item',
        'Extrair Processo Adm Processo Origem Adesão',
        'Extrair Processo Adm Processo Origem Adesão Itens',
        'Extrair Processo Adm Convidado',
        'Extrair Processo Adm Publicação',
        'Extrair Processo Adm Impugnação',
        'Extrair Processo Adm Sessão Julgamento',
        'Extrair Processo Adm Participante',
        'Extrair Processo Adm Participante Documento',
        'Extrair Processo Adm Participante Proposta',
        'Extrair Processo Adm Sessão Julgamento Ata',
        'Extrair Processo Adm Interposição Recurso',
        'Extrair Processo Adm Ato Final',
        'Extrair Processo Adm Ato Final Revogação',
        'Extrair Processo Adm Atualizar Valores',
        'Extrair Ata Registro Preço',
        'Extrair Ata Registro Preço Item',
        'Extrair Ata Registro Preço Ocorrência',
        'Extrair Ata Registro Preço Ocorrência Item',
        'Extrair Ata Registro Preço Atualizar Valores'
      ]
    }
  ],
  'Ponto': [
    {
      section: 'Dados Cadastrais',
      tasks: [
        'Extrair Cadastro de Horários',
        'Extrair Jornadas de Trabalho',
        'Extrair Cadastro de Turmas',
        'Extrair Motivos de Alteração de Ponto',
        'Extrair Tipos de Funções de Relógio',
        'Extrair Funções de Relógio',
        'Extrair Parâmetros do Ponto',
        'Extrair Tipos de Ausências'
      ]
    },
    {
      section: 'Dados de Lançamentos',
      tasks: [
        'Extrair Lançamento de Ausências',
        'Extrair Relógios',
        'Extrair Compensação de Horas',
        'Extrair Ocorrências do Ponto',
        'Extrair Períodos de Apuração do Ponto'
      ]
    }
  ],
  'Ponto (Cloud)': [
    {
      section: 'Dados Cadastrais',
      tasks: [
        'Extrair Cadastro de Horários',
        'Extrair Jornadas de Trabalho',
        'Extrair Cadastro de Turmas',
        'Extrair Motivos de Alteração de Ponto',
        'Extrair Tipos de Funções de Relógio',
        'Extrair Funções de Relógio',
        'Extrair Parâmetros do Ponto',
        'Extrair Tipos de Ausências'
      ]
    },
    {
      section: 'Dados de Lançamentos',
      tasks: [
        'Extrair Lançamento de Ausências',
        'Extrair Relógios',
        'Extrair Compensação de Horas',
        'Extrair Ocorrências do Ponto',
        'Extrair Períodos de Apuração do Ponto'
      ]
    }
  ],
  'Almoxarifado (Cloud)': [
    {
      section: 'Dados Cadastrais',
      tasks: [
        'Extrair Configuração Organograma',
        'Extrair Parâmetro Exercício',
        'Extrair Parâmetro Exercício Almoxarifado',
        'Extrair Centro Custo Movimentos',
        'Extrair Organograma Nível 1',
        'Extrair Organograma Nível 2',
        'Extrair Organograma Nível 3',
        'Extrair Países',
        'Extrair Estados',
        'Extrair Municípios',
        'Extrair Grupo',
        'Extrair Classe',
        'Extrair Unidade Medida',
        'Extrair Material',
        'Extrair Natureza',
        'Extrair Localização 1',
        'Extrair Localização 2',
        'Extrair Localização 3',
        'Extrair Cargos',
        'Extrair Responsável',
        'Extrair Fornecedor'
      ]
    },
    {
      section: 'Dados de Lançamentos',
      tasks: [
        'Extrair Requisições',
        'Extrair Requisições Item',
        'Extrair Lote',
        'Extrair Entradas',
        'Extrair Entradas Itens',
        'Extrair Entradas Itens Lotes',
        'Extrair Entradas Finalizar',
        'Extrair Saídas',
        'Extrair Saídas Itens',
        'Extrair Saídas Itens Lotes',
        'Extrair Saídas Finalizar',
        'Extrair Estoque',
        'Extrair Posição Estoque',
        'Extrair Movimento Atualização',
        'Extrair Encerramentos'
      ]
    }
  ],
  'Almoxarifado': [
    {
      section: 'Dados Cadastrais',
      tasks: [
        'Extrair Configuração Organograma',
        'Extrair Parâmetro Exercício',
        'Extrair Parâmetro Exercício Almoxarifado',
        'Extrair Centro Custo Movimentos',
        'Extrair Organograma Nível 1',
        'Extrair Organograma Nível 2',
        'Extrair Organograma Nível 3',
        'Extrair Países',
        'Extrair Estados',
        'Extrair Municípios',
        'Extrair Grupo',
        'Extrair Classe',
        'Extrair Unidade Medida',
        'Extrair Material',
        'Extrair Natureza',
        'Extrair Localização 1',
        'Extrair Localização 2',
        'Extrair Localização 3',
        'Extrair Cargos',
        'Extrair Responsável',
        'Extrair Fornecedor'
      ]
    },
    {
      section: 'Dados de Lançamentos',
      tasks: [
        'Extrair Requisições',
        'Extrair Requisições Item',
        'Extrair Lote',
        'Extrair Entradas',
        'Extrair Entradas Itens',
        'Extrair Entradas Itens Lotes',
        'Extrair Entradas Finalizar',
        'Extrair Saídas',
        'Extrair Saídas Itens',
        'Extrair Saídas Itens Lotes',
        'Extrair Saídas Finalizar',
        'Extrair Estoque',
        'Extrair Posição Estoque',
        'Extrair Movimento Atualização',
        'Extrair Encerramentos'
      ]
    }
  ],
  'Contratos (Cloud)': [
    {
      section: 'Dados Cadastrais',
      tasks: [
        'Extrair Tipo Instrumento Contratação',
        'Extrair Tipo Aditivo',
        'Extrair Tipo Publicação Contrato',
        'Extrair Tipo Administração',
        'Extrair Tipo Sanção',
        'Extrair Tipo Rescisão',
        'Extrair Motivo Rescisão',
        'Extrair Fonte Divulgação',
        'Extrair Tipo Comprovante',
        'Extrair Tipo Apostilamento',
        'Extrair Tipo Garantia',
        'Extrair Tipo Responsável Contrato'
      ]
    },
    {
      section: 'Dados de Lançamentos',
      tasks: [
        'Extrair Compras Diretas',
        'Extrair Compras Diretas Item',
        'Extrair Compras Diretas Despesa',
        'Extrair Compras Diretas Publicação',
        'Extrair Contratações',
        'Extrair Contratações Sem Processo',
        'Extrair Contratação Item',
        'Extrair Contratação Responsável Adm',
        'Extrair Contratação Publicação',
        'Extrair Contratação Despesa',
        'Extrair Contratação Textos',
        'Extrair Contratação Anexos',
        'Extrair Contratação Aditivo',
        'Extrair Contratação Aditivo Item',
        'Extrair Contratação Aditivo Sem Processo',
        'Extrair Contratação Aditivo Item Não Previsto',
        'Extrair Contratação Apostila',
        'Extrair Contratação Apostila Item',
        'Extrair Solicitação Fornecimento Compra Direta',
        'Extrair Solicitação Fornecimento Compra Direta Item',
        'Extrair Solicitação Fornecimento',
        'Extrair Solicitação Fornecimento Multi',
        'Extrair Solicitação Fornecimento Item',
        'Extrair Recebimento Compra Direta',
        'Extrair Recebimento Item Compra Direta',
        'Extrair Comprovante Compra Direta',
        'Extrair Comprovante Recebimentos',
        'Extrair Recebimento',
        'Extrair Recebimento Item',
        'Extrair Comprovante',
        'Extrair Comprovante Recebimentos',
        'Extrair Rescisão Contratual',
        'Extrair Sanção'
      ]
    }
  ],
  'Recursos Humanos': [
    {
      section: 'Dados Cadastrais',
      tasks: [
        'Extrair Distância',
        'Extrair Região',
        'Extrair Natureza Diária',
        'Extrair Diária',
        'Extrair Cursos',
        'Extrair Tipos Cursos',
        'Extrair Instituições',
        'Extrair Pessoas',
        'Extrair Pessoal Cursos',
        'Extrair Pessoal Filiação',
        'Extrair Pessoal Documento',
        'Extrair Pessoal Endereço',
        'Extrair Pessoal Email',
        'Extrair Pessoal Telefone',
        'Extrair Pessoal Dependente',
        'Extrair Pessoal Experiência',
        'Extrair Pessoal Averbação',
        'Extrair Pessoal Conta Bancária',
        'Extrair Pessoal Cota Sindical',
        'Extrair Pessoal Bolsa Estudos'
      ]
    }
  ],
  'Recursos Humanos (Cloud)': [
    {
      section: 'Dados Cadastrais',
      tasks: [
        'Extrair Distância',
        'Extrair Região',
        'Extrair Natureza Diária',
        'Extrair Diária',
        'Extrair Cursos',
        'Extrair Tipos Cursos',
        'Extrair Instituições',
        'Extrair Pessoas',
        'Extrair Pessoal Cursos',
        'Extrair Pessoal Filiação',
        'Extrair Pessoal Documento',
        'Extrair Pessoal Endereço',
        'Extrair Pessoal Email',
        'Extrair Pessoal Telefone',
        'Extrair Pessoal Dependente',
        'Extrair Pessoal Experiência',
        'Extrair Pessoal Averbação',
        'Extrair Pessoal Conta Bancária',
        'Extrair Pessoal Cota Sindical',
        'Extrair Pessoal Bolsa Estudos'
      ]
    }
  ],
  'Almoxarifado (Cloud)': [
    {
      section: 'Dados Cadastrais',
      tasks: [
        'Extrair Configuração Organograma',
        'Extrair Parâmetro Exercício',
        'Extrair Parâmetro Exercício Almoxarifado',
        'Extrair Centro Custo Movimentos',
        'Extrair Organograma Nível 1',
        'Extrair Organograma Nível 2',
        'Extrair Organograma Nível 3',
        'Extrair Países',
        'Extrair Estados',
        'Extrair Municípios',
        'Extrair Grupo',
        'Extrair Classe',
        'Extrair Unidade Medida',
        'Extrair Material',
        'Extrair Natureza',
        'Extrair Localização 1',
        'Extrair Localização 2',
        'Extrair Localização 3',
        'Extrair Cargos',
        'Extrair Responsável',
        'Extrair Fornecedor'
      ]
    },
    {
      section: 'Dados de Lançamentos',
      tasks: [
        'Extrair Requisições',
        'Extrair Requisições Item',
        'Extrair Lote',
        'Extrair Entradas',
        'Extrair Entradas Itens',
        'Extrair Entradas Itens Lotes',
        'Extrair Entradas Finalizar',
        'Extrair Saídas',
        'Extrair Saídas Itens',
        'Extrair Saídas Itens Lotes',
        'Extrair Saídas Finalizar',
        'Extrair Estoque',
        'Extrair Posição Estoque',
        'Extrair Movimento Atualização',
        'Extrair Encerramentos'
      ]
    }
  ],
  'Obras (Cloud)': [
    {
      section: 'Dados Cadastrais',
      tasks: [
        'OBRAS',
        'TIPOS DE OBRA',
        'CATEGORIAS',
        'ORGANOGRAMAS',
        'MEDIÇÕES',
        'SITUAÇÕES'
      ]
    }
  ],
  'Educação (Cloud)': parseTasksIntoSections([
    'Dados Cadastrais',
    'Extrair Países',
    'Extrair Estados',
    'Extrair Municípios',
    'Extrair Bairros',
    'Extrair Anos Letivos',
    'Extrair Escolas',
    'Extrair Turnos',
    'Extrair Modalidades de Ensino',
    'Extrair Etapas de Ensino',
    'Extrair Séries',
    'Extrair Salas de Aula',
    'Extrair Professores',
    'Extrair Funcionários',
    'Extrair Equipe Pedagógica',
    'Extrair Setores/Departamentos',
    'Extrair Turmas',
    'Extrair Alunos',
    'Extrair Matrículas',
    'Extrair Frequência de Alunos',
    'Extrair Planos de Aula',
    'Extrair Componentes Curriculares',
    'Extrair Avaliações',
    'Extrair Notas/Conceitos',
    'Extrair Documentos de Alunos',
    'Extrair Filiações de Alunos',
    'Extrair Responsáveis pelos Alunos',
    'Extrair Calendário Escolar',
    'Extrair Períodos Letivos',
    'Extrair Feriados',
    'Extrair Horários de Aula',
    'Extrair Jornada de Trabalho',
    'Extrair Dados de Contato (Escolas)',
    'Extrair Dados de Endereço (Escolas)',
    'Extrair Informações de Infraestrutura',
    'Extrair Programas e Projetos',
    'Extrair Indicadores Educacionais',
    'Extrair Recursos Financeiros',
    'Extrair Recursos Tecnológicos',
    'Extrair Bibliotecas',
    'Extrair Laboratórios',
    'Extrair Acervos Bibliográficos',
    'Extrair Equipamentos',
    'Extrair Relatórios Pedagógicos',
    'Extrair Históricos Escolares',
    'Extrair Certificados/Diplomas',
    'Extrair Movimentações de Alunos',
    'Extrair Evasão Escolar',
    'Extrair Desempenho Escolar',
    'Extrair Dados de Saúde (Vacinação)',
    'Extrair Dados de Transporte Escolar',
    'Extrair Dados de Alimentação Escolar',
    'Extrair Dados de Assistência Social',
    'Extrair Dados de Educação Especial',
    'Extrair Dados de EJA (Educação de Jovens e Adultos)',
    'Extrair Dados de Ensino Profissionalizante',
    'Extrair Dados de Ensino a Distância',
    'Extrair Dados de Ponto de Professores',
    'Extrair Dados de Ponto de Funcionários',
    'Extrair Dados de Folha de Pagamento',
    'Extrair Dados de Horas Extras',
    'Extrair Dados de Afastamentos',
    'Extrair Dados de Licenças',
    'Extrair Dados de Férias',
    'Extrair Dados de Rescisões',
    'Extrair Dados de Planos de Saúde',
    'Extrair Dados de Vale Refeição',
    'Extrair Dados de Vale Transporte',
    'Extrair Dados de Benefícios',
    'Extrair Dados de Previdência',
    'Extrair Dados de FGTS',
    'Extrair Dados de INSS',
    'Extrair Dados de IRRF',
    'Extrair Dados de PIS/PASEP',
    'Extrair Dados de Sindicatos',
    'Extrair Dados de Processos Administrativos',
    'Extrair Dados de Sindicâncias',
    'Extrair Dados de Comissões',
    'Extrair Dados de Eleições de Conselho',
    'Extrair Dados de Registros de Ponto Eletrônico',
    'Extrair Dados de Acesso ao Sistema',
    'Extrair Dados de Auditoria',
    'Extrair Dados de Manutenções Preventivas',
    'Extrair Dados de Reparos',
    'Extrair Dados de Contratos de Serviços',
    'Extrair Dados de Fornecedores',
    'Extrair Dados de Notas Fiscais',
    'Extrair Dados de Empenhos',
    'Extrair Dados de Licitações'
  ]),
  'Professores (Cloud)': parseTasksIntoSections([
    'Diário de Classe',
    'Diário aberto para a turma',
    'Frequência disponível',
    'Avaliações lançadas corretamente',
    'Conteúdos registrados',
    'Fechamento do diário realizado'
  ]),
  'Pais e Alunos (Cloud)': parseTasksIntoSections([
    'Pais e Alunos',
    'Geração e distribuição de acessos (tokens/chaves) para pais, alunos e responsáveis',
    'Habilitação da consulta online de desempenho escolar (notas, provas e atividades)',
    'Habilitação da consulta de frequência e emissão de boletim escolar online',
    'Configuração do ambiente para publicação de materiais, conteúdos e informativos pelos professores/gestores',
    'Parametrização da funcionalidade de registro de interesse por rematrícula online'
  ]),
  'Biblioteca (Cloud)': parseTasksIntoSections([
    'Dados Cadastrais',
    'Extrair Bibliotecas',
    'Extrair Títulos de Materiais',
    'Extrair Classificações Cutter',
    'Extrair Municípios',
    'Extrair Autores',
    'Extrair Assuntos',
    'Extrair Editoras',
    'Extrair Leitores',
    'Extrair Categorias de Materiais',
    'Extrair Tipos de Materiais',
    'Extrair Localizações',
    'Extrair Status de Materiais',
    'Extrair Configurações de Empréstimos',
    'Extrair Regras de Multa',
    'Dados de Lançamentos',
    'Extrair Exemplares de Materiais',
    'Extrair Empréstimos',
    'Extrair Devoluções',
    'Extrair Reservas',
    'Extrair Multas'
  ]),
  'Merenda Escolar (Cloud)': parseTasksIntoSections([
    'Merenda Escolar',
    'Cadastro de insumos/alimentos seguindo os padrões das tabelas TACO e IBGE',
    'Elaboração de receitas/cardápios com cálculo automático de informações nutricionais',
    'Mapeamento e registro de restrições alimentares e situação nutricional individual dos alunos',
    'Configuração do planejamento de demanda/quantidade (cálculo contra desperdício integrado à frequência)',
    'Acompanhamento de aferições de medidas e avaliação nutricional',
    'Registros de distribuição e consumo de refeições por turma',
    'Relatórios nutricionais e conformidade com diretrizes de alimentação escolar',
    'Integração com dados de frequência para ajuste automático de quantidades',
    'Configuração de fornecedores e registro de preços de insumos'
  ]),
  'Patrimonio': parseTasksIntoSections([
    'Dados Cadastrais',
    'Extrair Configuração Organograma',
    'Extrair Parâmetro Exercício',
    'Extrair Organograma',
    'Extrair Países',
    'Extrair Estados',
    'Extrair Municípios',
    'Extrair Bairros',
    'Extrair Logradouros',
    'Extrair Tipo Bem',
    'Extrair Estado Conservação',
    'Extrair Método Depreciação',
    'Extrair Localidade',
    'Extrair Responsável',
    'Extrair Fornecedor',
    'Dados de Lançamentos',
    'Extrair Bem Patrimonial',
    'Extrair Especificação Bem',
    'Extrair Entrada Bem',
    'Extrair Transferência Bem',
    'Extrair Saída Bem',
    'Extrair Depreciação',
    'Extrair Manutenção Bem',
    'Extrair Descarte Bem',
    'Extrair Movimentação Bem',
    'Extrair Componente Bem'
  ]),
  'Frotas (Cloud)': [
    {
      section: 'Dados Cadastrais',
      tasks: [
        'Extrair Configuração Organograma',
        'Extrair Parâmetro Exercício',
        'Extrair Organograma Órgão',
        'Extrair Organograma Unidade',
        'Extrair Organograma Centro Custo',
        'Extrair Países',
        'Extrair Estados',
        'Extrair Municípios',
        'Extrair Marca Veículo',
        'Extrair Modelo Veículo',
        'Extrair Tipo Veículo',
        'Extrair Tipo Despesa Frota',
        'Extrair Tipo Finalidade Reserva Veículo',
        'Extrair Tipo Taxa Licenciamento',
        'Extrair Rota',
        'Extrair Tipo Ocorrência Veículo',
        'Extrair Funcionário',
        'Extrair Fornecedor',
        'Extrair Motorista',
        'Extrair Parâmetro Notificação',
        'Extrair Veículo',
        'Extrair Veículo Agregado',
        'Extrair Veículo Combustível',
        'Extrair Veículo Organograma'
      ]
    },
    {
      section: 'Dados de Lançamentos',
      tasks: [
        'Extrair Reserva Veículo',
        'Extrair Controle Revisão',
        'Extrair Acompanhamento Mensal',
        'Extrair Taxa Licenciamento',
        'Extrair Taxa Licenciamento Parcela',
        'Extrair Ocorrência',
        'Extrair Ordem Abastecimento',
        'Extrair Ordem Abastecimento Item',
        'Extrair Lançamento Despesa',
        'Extrair Lançamento Despesa Item',
        'Extrair Controle Viagem',
        'Extrair Controle Viagem Finalidade',
        'Extrair Controle Viagem Rota'
      ]
    }
  ],
  'Almoxarifado (Cloud)': [
    {
      section: 'Dados Cadastrais',
      tasks: [
        'Extrair Configuração Organograma',
        'Extrair Parâmetro Exercício',
        'Extrair Parâmetro Exercício Almoxarifado',
        'Extrair Centro Custo Movimentos',
        'Extrair Organograma Nível 1',
        'Extrair Organograma Nível 2',
        'Extrair Organograma Nível 3',
        'Extrair Países',
        'Extrair Estados',
        'Extrair Municípios',
        'Extrair Grupo',
        'Extrair Classe',
        'Extrair Unidade Medida',
        'Extrair Material',
        'Extrair Natureza',
        'Extrair Localização 1',
        'Extrair Localização 2',
        'Extrair Localização 3',
        'Extrair Cargos',
        'Extrair Responsável',
        'Extrair Fornecedor'
      ]
    },
    {
      section: 'Dados de Lançamentos',
      tasks: [
        'Extrair Requisições',
        'Extrair Requisições Item',
        'Extrair Lote',
        'Extrair Entradas',
        'Extrair Entradas Itens',
        'Extrair Entradas Itens Lotes',
        'Extrair Entradas Finalizar',
        'Extrair Saídas',
        'Extrair Saídas Itens',
        'Extrair Saídas Itens Lotes',
        'Extrair Saídas Finalizar',
        'Extrair Estoque',
        'Extrair Posição Estoque',
        'Extrair Movimento Atualização',
        'Extrair Encerramentos'
      ]
    }
  ],
  'Almoxarifado': [
    {
      section: 'Dados Cadastrais',
      tasks: [
        'Extrair Configuração Organograma',
        'Extrair Parâmetro Exercício',
        'Extrair Parâmetro Exercício Almoxarifado',
        'Extrair Centro Custo Movimentos',
        'Extrair Organograma Nível 1',
        'Extrair Organograma Nível 2',
        'Extrair Organograma Nível 3',
        'Extrair Países',
        'Extrair Estados',
        'Extrair Municípios',
        'Extrair Grupo',
        'Extrair Classe',
        'Extrair Unidade Medida',
        'Extrair Material',
        'Extrair Natureza',
        'Extrair Localização 1',
        'Extrair Localização 2',
        'Extrair Localização 3',
        'Extrair Cargos',
        'Extrair Responsável',
        'Extrair Fornecedor'
      ]
    },
    {
      section: 'Dados de Lançamentos',
      tasks: [
        'Extrair Requisições',
        'Extrair Requisições Item',
        'Extrair Lote',
        'Extrair Entradas',
        'Extrair Entradas Itens',
        'Extrair Entradas Itens Lotes',
        'Extrair Entradas Finalizar',
        'Extrair Saídas',
        'Extrair Saídas Itens',
        'Extrair Saídas Itens Lotes',
        'Extrair Saídas Finalizar',
        'Extrair Estoque',
        'Extrair Posição Estoque',
        'Extrair Movimento Atualização',
        'Extrair Encerramentos'
      ]
    }
  ],
  'RH (Cloud)': [
    {
      section: 'Dados Cadastrais',
      tasks: [
        'Extrair Distância',
        'Extrair Região',
        'Extrair Natureza Diária',
        'Extrair Diária',
        'Extrair Cursos',
        'Extrair Tipos Cursos',
        'Extrair Instituições',
        'Extrair Pessoas',
        'Extrair Pessoal Cursos',
        'Extrair Pessoal Filiação',
        'Extrair Pessoal Documento',
        'Extrair Pessoal Endereço',
        'Extrair Pessoal Email',
        'Extrair Pessoal Telefone',
        'Extrair Pessoal Dependente',
        'Extrair Pessoal Experiência',
        'Extrair Pessoal Averbação',
        'Extrair Pessoal Conta Bancária',
        'Extrair Pessoal Cota Sindical',
        'Extrair Pessoal Bolsa Estudos'
      ]
    }
  ],
  'Portal do Gestor': parseTasksIntoSections([
    'Dados Cadastrais',
    'Informações Institucionais',
    'Configuração Geral',
    'Dados de Lançamentos',
    'Relatórios e Consultas'
  ]),
  'Saúde': [
    {
      section: 'Dados Cadastrais',
      tasks: [
        'Extrair Configurações Gerais',
        'Extrair Unidades de Saúde',
        'Extrair Setores/Departamentos',
        'Extrair Especialidades Médicas',
        'Extrair Equipamentos Médicos',
        'Extrair Medicamentos/Fármacos',
        'Extrair Testes/Exames Disponíveis',
        'Extrair Profissionais de Saúde',
        'Extrair Horários de Atendimento',
        'Extrair Convênios/Seguros'
      ]
    },
    {
      section: 'Dados de Pacientes',
      tasks: [
        'Extrair Dados Pessoais de Pacientes',
        'Extrair Documentos de Pacientes',
        'Extrair Contatos de Pacientes',
        'Extrair Endereços de Pacientes',
        'Extrair Alergias/Reações Adversas',
        'Extrair Histórico Médico',
        'Extrair Responsáveis/Acompanhantes',
        'Extrair Autorizações de Tratamento'
      ]
    },
    {
      section: 'Dados de Atendimento',
      tasks: [
        'Extrair Agendamentos',
        'Extrair Consultas Realizadas',
        'Extrair Prescrições Médicas',
        'Extrair Resultados de Exames',
        'Extrair Diagnósticos',
        'Extrair Procedimentos Realizados',
        'Extrair Notas de Internação',
        'Extrair Histórico de Tratamentos'
      ]
    },
    {
      section: 'Dados Financeiros e Administrativos',
      tasks: [
        'Extrair Faturamento de Procedimentos',
        'Extrair Faturamento de Consultas',
        'Extrair Faturamento de Exames',
        'Extrair Pagamentos de Pacientes',
        'Extrair Reembolsos de Convênios',
        'Extrair Gestão de Estoques',
        'Extrair Custos de Medicamentos'
      ]
    }
  ],
  'Saúde (Cloud)': [
    {
      section: 'Dados Cadastrais',
      tasks: [
        'Extrair Configurações Gerais',
        'Extrair Unidades de Saúde',
        'Extrair Setores/Departamentos',
        'Extrair Especialidades Médicas',
        'Extrair Equipamentos Médicos',
        'Extrair Medicamentos/Fármacos',
        'Extrair Testes/Exames Disponíveis',
        'Extrair Profissionais de Saúde',
        'Extrair Horários de Atendimento',
        'Extrair Convênios/Seguros'
      ]
    },
    {
      section: 'Dados de Pacientes',
      tasks: [
        'Extrair Dados Pessoais de Pacientes',
        'Extrair Documentos de Pacientes',
        'Extrair Contatos de Pacientes',
        'Extrair Endereços de Pacientes',
        'Extrair Alergias/Reações Adversas',
        'Extrair Histórico Médico',
        'Extrair Responsáveis/Acompanhantes',
        'Extrair Autorizações de Tratamento'
      ]
    },
    {
      section: 'Dados de Atendimento',
      tasks: [
        'Extrair Agendamentos',
        'Extrair Consultas Realizadas',
        'Extrair Prescrições Médicas',
        'Extrair Resultados de Exames',
        'Extrair Diagnósticos',
        'Extrair Procedimentos Realizados',
        'Extrair Notas de Internação',
        'Extrair Histórico de Tratamentos'
      ]
    },
    {
      section: 'Dados Financeiros e Administrativos',
      tasks: [
        'Extrair Faturamento de Procedimentos',
        'Extrair Faturamento de Consultas',
        'Extrair Faturamento de Exames',
        'Extrair Pagamentos de Pacientes',
        'Extrair Reembolsos de Convênios',
        'Extrair Gestão de Estoques',
        'Extrair Custos de Medicamentos'
      ]
    }
  ]
};

// Normaliza o nome do produto removendo "(Cloud)" e caracteres especiais
const normalizeProductName = (name) => {
  if (!name) return '';
  return name
    .toLowerCase()
    .replace(/\(cloud\)/gi, '')
    .replace(/[()]/g, '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '') // Remove acentos
    .trim()
    .replace(/\s+/g, ' ');
};

// Função para buscar tarefas por nome de produto
// Retorna null se o produto não tiver processo de migração
export const getDefaultTasksForProduct = (productName) => {
  if (!productName) return null;
  
  const normalized = (productName || '').toLowerCase().replace(/\(cloud\)/gi, '').trim();
  return migrationTasksByProduct[normalized] || null;
};

// Verifica se um produto tem processo de migração
export const productHasMigration = (productName) => {
  return getDefaultTasksForProduct(productName) !== null;
};